# This file is part of the openHiTLS project.
#
# openHiTLS is licensed under the Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#     http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.


# Mark preset as loaded (prevents profile system from overriding)
set(HITLS_PRESET_LOADED         ON CACHE BOOL "" FORCE)

# Platform
set(HITLS_PLATFORM_BITS         "64" CACHE STRING "" FORCE)
set(HITLS_ASM_ARMV8             ON CACHE BOOL "" FORCE)

# Build type
set(HITLS_BUILD_STATIC          ON CACHE BOOL "" FORCE)
set(HITLS_BUILD_SHARED          ON CACHE BOOL "" FORCE)

# BSL modules
set(HITLS_BSL_ASN1              ON CACHE BOOL "" FORCE)
set(HITLS_BSL_ERR               ON CACHE BOOL "" FORCE)
set(HITLS_BSL_HASH              ON CACHE BOOL "" FORCE)
set(HITLS_BSL_INIT              ON CACHE BOOL "" FORCE)
set(HITLS_BSL_LIST              ON CACHE BOOL "" FORCE)
set(HITLS_BSL_OBJ               ON CACHE BOOL "" FORCE)
set(HITLS_BSL_PARAMS            ON CACHE BOOL "" FORCE)
set(HITLS_BSL_PEM               ON CACHE BOOL "" FORCE)
set(HITLS_BSL_SAL               ON CACHE BOOL "" FORCE)
set(HITLS_BSL_SAL_DL            ON CACHE BOOL "" FORCE)
set(HITLS_BSL_SAL_LOCK          ON CACHE BOOL "" FORCE)
set(HITLS_BSL_SAL_MEM           ON CACHE BOOL "" FORCE)
set(HITLS_BSL_SAL_STR           ON CACHE BOOL "" FORCE)
set(HITLS_BSL_SAL_THREAD        ON CACHE BOOL "" FORCE)
set(HITLS_BSL_SAL_TIME          ON CACHE BOOL "" FORCE)
set(HITLS_BSL_UIO_PLT           ON CACHE BOOL "" FORCE)

# Crypto modules
set(HITLS_CRYPTO_EAL            ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_EALINIT        ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_SM3            ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_HMAC           ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_CBC_MAC        ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_PBKDF2         ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_KDFTLS12       ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_DRBG_HASH      ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_DRBG_CTR       ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_ENTROPY        ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_KEY_ENCODE     ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_KEY_DECODE     ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_KEY_DECODE_CHAIN ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_CODECS         ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_KEY_EPKI       ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_CBC            ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_ECB            ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_GCM            ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_OFB            ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_CFB            ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_CTR            ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_XTS            ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_SM4            ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_SM2            ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_PROVIDER       ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_BN             ON CACHE BOOL "" FORCE)

# Other
set(HITLS_CRYPTO_DRBG_GM        ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_ENTROPY_SYS    ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_RAND_CB        ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_ENTROPY_GM_CF  ON CACHE BOOL "" FORCE)
set(HITLS_CRYPTO_DRBG_GM_LEVEL "1" CACHE STRING "" FORCE)
set(HITLS_SEED_DRBG_INIT_RAND_ALG "CRYPT_RAND_SM4_CTR_DF" CACHE STRING "" FORCE)


# Linker flags
set(CMAKE_SHARED_LINKER_FLAGS
    "-Wl,--version-script=${CMAKE_SOURCE_DIR}/testcode/config/cmake/CMVP/libhitls_cmvp.ld"
    CACHE STRING "Shared library linker flags (optional)" FORCE
)
