# This file is part of the openHiTLS project.
#
# openHiTLS is licensed under the Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#     http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.


# ==============================================================================
# This file defines the dependencies(compile related) between modules/features in the HiTLS library. 
# It is used to ensure that when a feature is enabled, all of its dependencies are also enabled.
# The dependencies are includes two parts:
#   1. The parent modules/features that decide whether the current module/feature is enabled or not.
#   2. The modules/features that are required by the current module/feature to work properly.
# ==============================================================================

include_guard(GLOBAL)

include(helpers/hitls_depends_helpers)

# --- Dependency Definitions ---

# Top-level library switches - carry no DEPS themselves but define CHILDREN so
# that enabling a library switch automatically expands all first-level sub-features.
# Sub-features declare their own CHILDREN, enabling full recursive expansion.
hitls_define_dependency(HITLS_BSL
    CHILDREN
        HITLS_BSL_SAL        HITLS_BSL_SAL_DL     HITLS_BSL_SAL_FILE
        HITLS_BSL_SAL_LOCK   HITLS_BSL_SAL_MEM    HITLS_BSL_SAL_NET
        HITLS_BSL_SAL_STR    HITLS_BSL_SAL_THREAD HITLS_BSL_SAL_TIME
        HITLS_BSL_SAL_PID    HITLS_BSL_SAL_IP
        HITLS_BSL_ASN1       HITLS_BSL_BASE64     HITLS_BSL_BUFFER
        HITLS_BSL_CONF       HITLS_BSL_ERR        HITLS_BSL_HASH
        HITLS_BSL_INIT       HITLS_BSL_LIST       HITLS_BSL_LOG
        HITLS_BSL_OBJ        HITLS_BSL_PARAMS     HITLS_BSL_PEM
        HITLS_BSL_PRINT      HITLS_BSL_TLV        HITLS_BSL_UI
        HITLS_BSL_UIO
)

# BSL Dependencies
hitls_define_dependency(HITLS_BSL_SAL               DEPS HITLS_BSL)
hitls_define_dependency(HITLS_BSL_SAL_FILE          DEPS HITLS_BSL)
hitls_define_dependency(HITLS_BSL_SAL_NET           DEPS HITLS_BSL)
hitls_define_dependency(HITLS_BSL_SAL_DL            DEPS HITLS_BSL)
hitls_define_dependency(HITLS_BSL_SAL_LOCK          DEPS HITLS_BSL)
hitls_define_dependency(HITLS_BSL_SAL_THREAD        DEPS HITLS_BSL)
hitls_define_dependency(HITLS_BSL_SAL_TIME          DEPS HITLS_BSL)
hitls_define_dependency(HITLS_BSL_SAL_STR           DEPS HITLS_BSL)
hitls_define_dependency(HITLS_BSL_SAL_MEM           DEPS HITLS_BSL)
hitls_define_dependency(HITLS_BSL_SAL_PID           DEPS HITLS_BSL)
hitls_define_dependency(HITLS_BSL_SAL_IP            DEPS HITLS_BSL)
hitls_define_dependency(HITLS_BSL_ASN1              DEPS HITLS_BSL HITLS_BSL_SAL HITLS_BSL_SAL_TIME)
hitls_define_dependency(HITLS_BSL_BASE64            DEPS HITLS_BSL HITLS_BSL_SAL)
hitls_define_dependency(HITLS_BSL_BUFFER            DEPS HITLS_BSL HITLS_BSL_SAL)
hitls_define_dependency(HITLS_BSL_CONF              DEPS HITLS_BSL HITLS_BSL_SAL HITLS_BSL_UIO_FILE HITLS_BSL_LIST)
hitls_define_dependency(HITLS_BSL_ERR               DEPS HITLS_BSL HITLS_BSL_SAL)
hitls_define_dependency(HITLS_BSL_HASH              DEPS HITLS_BSL HITLS_BSL_SAL)
hitls_define_dependency(HITLS_BSL_INIT              DEPS HITLS_BSL HITLS_BSL_SAL HITLS_BSL_ERR)
hitls_define_dependency(HITLS_BSL_LIST              DEPS HITLS_BSL HITLS_BSL_SAL)
hitls_define_dependency(HITLS_BSL_LOG               DEPS HITLS_BSL HITLS_BSL_SAL)
hitls_define_dependency(HITLS_BSL_OBJ
    DEPS HITLS_BSL HITLS_BSL_SAL
    CHILDREN HITLS_BSL_OBJ_DEFAULT HITLS_BSL_OBJ_CUSTOM
)
hitls_define_dependency(HITLS_BSL_OBJ_DEFAULT           DEPS HITLS_BSL_OBJ)
hitls_define_dependency(HITLS_BSL_OBJ_CUSTOM            DEPS HITLS_BSL_OBJ HITLS_BSL_HASH)
hitls_define_dependency(HITLS_BSL_PARAMS            DEPS HITLS_BSL HITLS_BSL_SAL HITLS_BSL_LIST)
hitls_define_dependency(HITLS_BSL_PEM               DEPS HITLS_BSL HITLS_BSL_SAL HITLS_BSL_BASE64)
hitls_define_dependency(HITLS_BSL_PRINT             DEPS HITLS_BSL HITLS_BSL_SAL)
hitls_define_dependency(HITLS_BSL_TLV               DEPS HITLS_BSL HITLS_BSL_SAL)
hitls_define_dependency(HITLS_BSL_UI                DEPS HITLS_BSL HITLS_BSL_SAL HITLS_BSL_SAL_FILE)
hitls_define_dependency(HITLS_BSL_UIO
    DEPS HITLS_BSL HITLS_BSL_SAL
    CHILDREN
        HITLS_BSL_UIO_BUFFER HITLS_BSL_UIO_FILE   HITLS_BSL_UIO_MEM
        HITLS_BSL_UIO_PLT    HITLS_BSL_UIO_SCTP   HITLS_BSL_UIO_TCP
        HITLS_BSL_UIO_UDP
)
hitls_define_dependency(HITLS_BSL_UIO_BUFFER            DEPS HITLS_BSL_UIO HITLS_BSL_UIO_PLT)
hitls_define_dependency(HITLS_BSL_UIO_FILE              DEPS HITLS_BSL_UIO HITLS_BSL_UIO_PLT HITLS_BSL_SAL_FILE)
hitls_define_dependency(HITLS_BSL_UIO_MEM               DEPS HITLS_BSL_UIO HITLS_BSL_UIO_PLT HITLS_BSL_BUFFER)
hitls_define_dependency(HITLS_BSL_UIO_PLT               DEPS HITLS_BSL_UIO)
hitls_define_dependency(HITLS_BSL_UIO_SCTP              DEPS HITLS_BSL_UIO HITLS_BSL_UIO_PLT HITLS_BSL_SAL_NET)
hitls_define_dependency(HITLS_BSL_UIO_TCP               DEPS HITLS_BSL_UIO HITLS_BSL_UIO_PLT HITLS_BSL_SAL_NET)
hitls_define_dependency(HITLS_BSL_UIO_UDP               DEPS HITLS_BSL_UIO HITLS_BSL_UIO_PLT HITLS_BSL_SAL_NET)

# CRYPTO Dependencies
hitls_define_dependency(HITLS_CRYPTO
    DEPS HITLS_BSL_SAL
    CHILDREN
        HITLS_CRYPTO_EAL        HITLS_CRYPTO_EALINIT
        HITLS_CRYPTO_MD         HITLS_CRYPTO_MD_MB
        HITLS_CRYPTO_MAC        HITLS_CRYPTO_HPKE
        HITLS_CRYPTO_KDF        HITLS_CRYPTO_DRBG
        HITLS_CRYPTO_ENTROPY    HITLS_CRYPTO_MODES
        HITLS_CRYPTO_CIPHER     HITLS_CRYPTO_PKEY
        HITLS_CRYPTO_PKEY_CMP   HITLS_CRYPTO_PROVIDER
        HITLS_CRYPTO_BN         HITLS_CRYPTO_CODECSKEY
        HITLS_CRYPTO_KEY_DECODE_CHAIN   HITLS_CRYPTO_CODECS
        HITLS_CRYPTO_GHASH
)
## Bn
hitls_define_dependency(HITLS_CRYPTO_BN
    DEPS HITLS_CRYPTO
    CHILDREN
        HITLS_CRYPTO_BN_BASIC   HITLS_CRYPTO_BN_RAND   HITLS_CRYPTO_BN_PRIME
        HITLS_CRYPTO_BN_RFC_PRIME HITLS_CRYPTO_BN_STR_CONV HITLS_CRYPTO_BN_CB
)
hitls_define_dependency(HITLS_CRYPTO_BN_BASIC           DEPS HITLS_CRYPTO_BN)
hitls_define_dependency(HITLS_CRYPTO_BN_RAND            DEPS HITLS_CRYPTO_BN)
hitls_define_dependency(HITLS_CRYPTO_BN_PRIME           DEPS HITLS_CRYPTO_BN HITLS_CRYPTO_BN_RAND)
hitls_define_dependency(HITLS_CRYPTO_BN_RFC_PRIME       DEPS HITLS_CRYPTO_BN)
hitls_define_dependency(HITLS_CRYPTO_BN_STR_CONV        DEPS HITLS_CRYPTO_BN)
hitls_define_dependency(HITLS_CRYPTO_BN_CB              DEPS HITLS_CRYPTO_BN)
hitls_define_dependency(HITLS_CRYPTO_EAL_BN             DEPS HITLS_CRYPTO_BN)
## drbg
hitls_define_dependency(HITLS_CRYPTO_DRBG
    DEPS HITLS_CRYPTO HITLS_BSL_SAL_PID
    CHILDREN HITLS_CRYPTO_DRBG_HASH HITLS_CRYPTO_DRBG_HMAC HITLS_CRYPTO_DRBG_CTR
)
hitls_define_dependency(HITLS_CRYPTO_DRBG_CTR           DEPS HITLS_CRYPTO_DRBG)
hitls_define_dependency(HITLS_CRYPTO_DRBG_HASH
    DEPS HITLS_CRYPTO_DRBG
    DEPS_CHECK HITLS_CRYPTO_MD
)
hitls_define_dependency(HITLS_CRYPTO_DRBG_HMAC          DEPS HITLS_CRYPTO_DRBG HITLS_CRYPTO_HMAC)
hitls_define_dependency(HITLS_CRYPTO_DRBG_GM            DEPS HITLS_CRYPTO_DRBG HITLS_BSL_SAL_TIME)
## Entropy
hitls_define_dependency(HITLS_CRYPTO_ENTROPY
    DEPS HITLS_CRYPTO HITLS_BSL_LIST
    DEPS_CHECK HITLS_CRYPTO_DRBG
)
hitls_define_dependency(HITLS_CRYPTO_ENTROPY_HARDWARE
    DEPS HITLS_CRYPTO_ENTROPY
    DEPS_CHECK HITLS_CRYPTO_EALINIT
)
hitls_define_dependency(HITLS_CRYPTO_ENTROPY_DEVRANDOM  DEPS HITLS_CRYPTO_ENTROPY)
hitls_define_dependency(HITLS_CRYPTO_ENTROPY_GETENTROPY DEPS HITLS_CRYPTO_ENTROPY)
hitls_define_dependency(HITLS_CRYPTO_ENTROPY_SYS        DEPS HITLS_CRYPTO_ENTROPY HITLS_BSL_SAL_TIME)
## Eal
hitls_define_dependency(HITLS_CRYPTO_EAL                DEPS HITLS_CRYPTO HITLS_BSL_INIT)
hitls_define_dependency(HITLS_CRYPTO_ENTROPY_GM_CF      DEPS HITLS_CRYPTO_EAL HITLS_CRYPTO_ENTROPY)
## EalInit
hitls_define_dependency(HITLS_CRYPTO_EALINIT            DEPS HITLS_CRYPTO)
## Cipher
hitls_define_dependency(HITLS_CRYPTO_CIPHER
    DEPS HITLS_CRYPTO
    CHILDREN HITLS_CRYPTO_AES HITLS_CRYPTO_SM4 HITLS_CRYPTO_CHACHA20
)
hitls_define_dependency(HITLS_CRYPTO_AES                DEPS HITLS_CRYPTO_CIPHER)
hitls_define_dependency(HITLS_CRYPTO_SM4                DEPS HITLS_CRYPTO_CIPHER)
hitls_define_dependency(HITLS_CRYPTO_CHACHA20           DEPS HITLS_CRYPTO_CIPHER HITLS_CRYPTO_CHACHA20POLY1305)
## Modes
hitls_define_dependency(HITLS_CRYPTO_MODES
    DEPS HITLS_CRYPTO HITLS_CRYPTO_EAL
    CHILDREN
        HITLS_CRYPTO_CTR  HITLS_CRYPTO_CBC  HITLS_CRYPTO_ECB  HITLS_CRYPTO_GCM
        HITLS_CRYPTO_CCM  HITLS_CRYPTO_XTS  HITLS_CRYPTO_CFB  HITLS_CRYPTO_OFB
        HITLS_CRYPTO_WRAP HITLS_CRYPTO_CHACHA20POLY1305 HITLS_CRYPTO_HCTR
)
hitls_define_dependency(HITLS_CRYPTO_GCM                DEPS HITLS_CRYPTO_MODES HITLS_CRYPTO_GHASH)
hitls_define_dependency(HITLS_CRYPTO_CBC                DEPS HITLS_CRYPTO_MODES)
hitls_define_dependency(HITLS_CRYPTO_CTR                DEPS HITLS_CRYPTO_MODES)
hitls_define_dependency(HITLS_CRYPTO_CCM                DEPS HITLS_CRYPTO_MODES)
hitls_define_dependency(HITLS_CRYPTO_ECB                DEPS HITLS_CRYPTO_MODES)
hitls_define_dependency(HITLS_CRYPTO_XTS                DEPS HITLS_CRYPTO_MODES)
hitls_define_dependency(HITLS_CRYPTO_CFB                DEPS HITLS_CRYPTO_MODES)
hitls_define_dependency(HITLS_CRYPTO_OFB                DEPS HITLS_CRYPTO_MODES)
hitls_define_dependency(HITLS_CRYPTO_HCTR               DEPS HITLS_CRYPTO_MODES)
hitls_define_dependency(HITLS_CRYPTO_CHACHA20POLY1305   DEPS HITLS_CRYPTO_MODES)
hitls_define_dependency(HITLS_CRYPTO_WRAP               DEPS HITLS_CRYPTO_MODES)
hitls_define_dependency(HITLS_CRYPTO_GHASH              DEPS HITLS_CRYPTO_MODES)
## Hash
hitls_define_dependency(HITLS_CRYPTO_MD
    DEPS HITLS_CRYPTO
    CHILDREN HITLS_CRYPTO_MD5 HITLS_CRYPTO_SM3 HITLS_CRYPTO_SHA1 HITLS_CRYPTO_SHA2 HITLS_CRYPTO_SHA3
)
hitls_define_dependency(HITLS_CRYPTO_MD5                DEPS HITLS_CRYPTO_MD)
hitls_define_dependency(HITLS_CRYPTO_SHA1               DEPS HITLS_CRYPTO_MD)
hitls_define_dependency(HITLS_CRYPTO_SHA2
    DEPS HITLS_CRYPTO_MD
    CHILDREN HITLS_CRYPTO_SHA224 HITLS_CRYPTO_SHA256 HITLS_CRYPTO_SHA384 HITLS_CRYPTO_SHA512
)
hitls_define_dependency(HITLS_CRYPTO_SHA256             DEPS HITLS_CRYPTO_SHA2)
hitls_define_dependency(HITLS_CRYPTO_SHA512             DEPS HITLS_CRYPTO_SHA2)
hitls_define_dependency(HITLS_CRYPTO_SHA224             DEPS HITLS_CRYPTO_SHA256)
hitls_define_dependency(HITLS_CRYPTO_SHA384             DEPS HITLS_CRYPTO_SHA512)
hitls_define_dependency(HITLS_CRYPTO_SHA3               DEPS HITLS_CRYPTO_MD)
hitls_define_dependency(HITLS_CRYPTO_SM3                DEPS HITLS_CRYPTO_MD)
hitls_define_dependency(HITLS_CRYPTO_MD_MB
    DEPS HITLS_CRYPTO_MD
    CHILDREN HITLS_CRYPTO_SHA2_MB
)
hitls_define_dependency(HITLS_CRYPTO_SHA2_MB
    DEPS HITLS_CRYPTO_MD_MB
    CHILDREN HITLS_CRYPTO_SHA256_MB
)
hitls_define_dependency(HITLS_CRYPTO_SHA256_MB          DEPS HITLS_CRYPTO_SHA2_MB HITLS_CRYPTO_SHA256)
hitls_define_dependency(HITLS_CRYPTO_SHA256_SMALL_MEM   DEPS HITLS_CRYPTO_SHA256)
hitls_define_dependency(HITLS_CRYPTO_SHA512_SMALL_MEM   DEPS HITLS_CRYPTO_SHA512)
hitls_define_dependency(HITLS_CRYPTO_SHA1_SMALL_MEM     DEPS HITLS_CRYPTO_SHA1)

## Mac
hitls_define_dependency(HITLS_CRYPTO_MAC
    DEPS HITLS_CRYPTO
    CHILDREN
        HITLS_CRYPTO_HMAC   HITLS_CRYPTO_CMAC   HITLS_CRYPTO_GMAC
        HITLS_CRYPTO_SIPHASH HITLS_CRYPTO_CBC_MAC
)
hitls_define_dependency(HITLS_CRYPTO_HMAC
    DEPS HITLS_CRYPTO_MAC
    DEPS_CHECK HITLS_CRYPTO_MD
)
hitls_define_dependency(HITLS_CRYPTO_CMAC
    DEPS HITLS_CRYPTO_MAC
    CHILDREN HITLS_CRYPTO_CMAC_AES HITLS_CRYPTO_CMAC_SM4
)
hitls_define_dependency(HITLS_CRYPTO_CMAC_AES           DEPS HITLS_CRYPTO_CMAC HITLS_CRYPTO_AES)
hitls_define_dependency(HITLS_CRYPTO_CMAC_SM4           DEPS HITLS_CRYPTO_CMAC HITLS_CRYPTO_SM4)
hitls_define_dependency(HITLS_CRYPTO_CBC_MAC            DEPS HITLS_CRYPTO_MAC HITLS_CRYPTO_SM4)
hitls_define_dependency(HITLS_CRYPTO_GMAC
    DEPS HITLS_CRYPTO_MAC HITLS_CRYPTO_EAL HITLS_CRYPTO_GCM HITLS_CRYPTO_AES
)
hitls_define_dependency(HITLS_CRYPTO_SIPHASH            DEPS HITLS_CRYPTO_MAC)
## Kdf
hitls_define_dependency(HITLS_CRYPTO_KDF
    DEPS HITLS_CRYPTO HITLS_CRYPTO_HMAC HITLS_BSL_PARAMS
    CHILDREN HITLS_CRYPTO_PBKDF2 HITLS_CRYPTO_HKDF HITLS_CRYPTO_KDFTLS12 HITLS_CRYPTO_SCRYPT
)
hitls_define_dependency(HITLS_CRYPTO_HKDF               DEPS HITLS_CRYPTO_KDF)
hitls_define_dependency(HITLS_CRYPTO_PBKDF2             DEPS HITLS_CRYPTO_KDF)
hitls_define_dependency(HITLS_CRYPTO_SCRYPT             DEPS HITLS_CRYPTO_KDF HITLS_CRYPTO_SHA256 HITLS_CRYPTO_PBKDF2)
hitls_define_dependency(HITLS_CRYPTO_KDFTLS12           DEPS HITLS_CRYPTO_KDF)
## CodecsKey
hitls_define_dependency(HITLS_CRYPTO_CODECSKEY
    DEPS HITLS_CRYPTO HITLS_BSL_ASN1 HITLS_BSL_OBJ_DEFAULT
    CHILDREN HITLS_CRYPTO_KEY_ENCODE HITLS_CRYPTO_KEY_DECODE HITLS_CRYPTO_KEY_EPKI HITLS_CRYPTO_KEY_INFO
)
hitls_define_dependency(HITLS_CRYPTO_KEY_ENCODE         DEPS HITLS_CRYPTO_CODECSKEY)
hitls_define_dependency(HITLS_CRYPTO_KEY_DECODE         DEPS HITLS_CRYPTO_CODECSKEY HITLS_BSL_PARAMS)
hitls_define_dependency(HITLS_CRYPTO_KEY_DECODE_CHAIN
    DEPS HITLS_CRYPTO_KEY_DECODE HITLS_CRYPTO_CODECS HITLS_BSL_PARAMS
)
hitls_define_dependency(HITLS_CRYPTO_KEY_EPKI
    DEPS HITLS_CRYPTO_CODECSKEY HITLS_CRYPTO_PBKDF2 HITLS_BSL_PARAMS
    DEPS_CHECK HITLS_CRYPTO_CIPHER HITLS_CRYPTO_DRBG
)
hitls_define_dependency(HITLS_CRYPTO_KEY_INFO           DEPS HITLS_CRYPTO_CODECSKEY HITLS_BSL_PRINT HITLS_CRYPTO_PKEY)
## Asymetric(Pkey)
hitls_define_dependency(HITLS_CRYPTO_PKEY
    DEPS HITLS_CRYPTO HITLS_BSL_PARAMS
    CHILDREN HITLS_CRYPTO_PKEY_CMP
        HITLS_CRYPTO_RSA        HITLS_CRYPTO_RSA_BSSA  HITLS_CRYPTO_CURVE25519
        HITLS_CRYPTO_DSA        HITLS_CRYPTO_DH        HITLS_CRYPTO_ECC
        HITLS_CRYPTO_ECDH       HITLS_CRYPTO_ECDSA     HITLS_CRYPTO_SM2
        HITLS_CRYPTO_SM9        HITLS_CRYPTO_PAILLIER  HITLS_CRYPTO_ELGAMAL
        HITLS_CRYPTO_MLKEM      HITLS_CRYPTO_FRODOKEM
        HITLS_CRYPTO_MCELIECE                  HITLS_CRYPTO_MLDSA
        HITLS_CRYPTO_HYBRIDKEM  HITLS_CRYPTO_SLH_DSA   HITLS_CRYPTO_XMSS
)
hitls_define_dependency(HITLS_CRYPTO_PKEY_CMP
    CHILDREN
        HITLS_CRYPTO_RSA_CMP        HITLS_CRYPTO_DSA_CMP
        HITLS_CRYPTO_DH_CMP         HITLS_CRYPTO_ECDSA_CMP
        HITLS_CRYPTO_ECDH_CMP       HITLS_CRYPTO_SM2_CMP
        HITLS_CRYPTO_CURVE25519_CMP HITLS_CRYPTO_MLDSA_CMP
        HITLS_CRYPTO_MLKEM_CMP      HITLS_CRYPTO_SM9_CMP
        HITLS_CRYPTO_FRODOKEM_CMP   HITLS_CRYPTO_MCELIECE_CMP
)
hitls_define_dependency(HITLS_CRYPTO_DSA
    DEPS HITLS_CRYPTO_PKEY
        HITLS_CRYPTO_PKEY_SIGN HITLS_CRYPTO_BN_RAND HITLS_CRYPTO_MD HITLS_BSL_ASN1
    CHILDREN HITLS_CRYPTO_DSA_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_DSA_CHECK          DEPS HITLS_CRYPTO_DSA)
hitls_define_dependency(HITLS_CRYPTO_DSA_GEN_PARA       DEPS HITLS_CRYPTO_DSA)
hitls_define_dependency(HITLS_CRYPTO_CURVE25519
    DEPS HITLS_CRYPTO_PKEY
    CHILDREN HITLS_CRYPTO_X25519 HITLS_CRYPTO_ED25519 HITLS_CRYPTO_X25519_CHECK HITLS_CRYPTO_ED25519_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_ED25519
    DEPS HITLS_CRYPTO_CURVE25519 HITLS_CRYPTO_PKEY_SIGN HITLS_CRYPTO_SHA512 HITLS_BSL_PARAMS
)
hitls_define_dependency(HITLS_CRYPTO_ED25519_CHECK      DEPS HITLS_CRYPTO_ED25519)
hitls_define_dependency(HITLS_CRYPTO_X25519
    DEPS HITLS_CRYPTO_CURVE25519 HITLS_CRYPTO_PKEY_EXCH HITLS_BSL_PARAMS
)
hitls_define_dependency(HITLS_CRYPTO_X25519_CHECK       DEPS HITLS_CRYPTO_X25519)
hitls_define_dependency(HITLS_CRYPTO_RSA
    DEPS HITLS_CRYPTO_PKEY HITLS_CRYPTO_BN_BASIC
    CHILDREN
        HITLS_CRYPTO_RSA_SIGN   HITLS_CRYPTO_RSA_VERIFY  HITLS_CRYPTO_RSA_RECOVER
        HITLS_CRYPTO_RSA_ENCRYPT HITLS_CRYPTO_RSA_DECRYPT HITLS_CRYPTO_RSA_BLINDING
        HITLS_CRYPTO_RSA_GEN    HITLS_CRYPTO_RSA_PAD     HITLS_CRYPTO_RSA_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_RSA_GEN
    DEPS HITLS_CRYPTO_RSA HITLS_CRYPTO_BN_RAND HITLS_CRYPTO_BN_PRIME
)
hitls_define_dependency(HITLS_CRYPTO_RSA_SIGN           DEPS HITLS_CRYPTO_RSA HITLS_CRYPTO_PKEY_SIGN HITLS_CRYPTO_MD)
hitls_define_dependency(HITLS_CRYPTO_RSA_VERIFY         DEPS HITLS_CRYPTO_RSA HITLS_CRYPTO_PKEY_SIGN HITLS_CRYPTO_MD)
hitls_define_dependency(HITLS_CRYPTO_RSA_RECOVER        DEPS HITLS_CRYPTO_RSA HITLS_CRYPTO_RSA_VERIFY)
hitls_define_dependency(HITLS_CRYPTO_RSA_ENCRYPT        DEPS HITLS_CRYPTO_RSA HITLS_CRYPTO_PKEY_CRYPT)
hitls_define_dependency(HITLS_CRYPTO_RSA_DECRYPT        DEPS HITLS_CRYPTO_RSA HITLS_CRYPTO_PKEY_CRYPT)
hitls_define_dependency(HITLS_CRYPTO_RSA_PAD
    DEPS HITLS_CRYPTO_RSA
    CHILDREN
        HITLS_CRYPTO_RSA_EMSA_PSS       HITLS_CRYPTO_RSA_EMSA_ISO9796_2
        HITLS_CRYPTO_RSA_EMSA_PKCSV15   HITLS_CRYPTO_RSAES_OAEP
        HITLS_CRYPTO_RSAES_PKCSV15      HITLS_CRYPTO_RSAES_PKCSV15_TLS
        HITLS_CRYPTO_RSA_NO_PAD
)
hitls_define_dependency(HITLS_CRYPTO_RSA_NO_PAD         DEPS HITLS_CRYPTO_RSA_PAD)
hitls_define_dependency(HITLS_CRYPTO_RSAES_OAEP         DEPS HITLS_CRYPTO_RSA_PAD HITLS_BSL_PARAMS)
hitls_define_dependency(HITLS_CRYPTO_RSAES_PKCSV15      DEPS HITLS_CRYPTO_RSA_PAD)
hitls_define_dependency(HITLS_CRYPTO_RSAES_PKCSV15_TLS  DEPS HITLS_CRYPTO_RSA_PAD)
hitls_define_dependency(HITLS_CRYPTO_RSA_EMSA_ISO9796_2 DEPS HITLS_CRYPTO_RSA_PAD HITLS_BSL_PARAMS)
hitls_define_dependency(HITLS_CRYPTO_RSA_EMSA_PKCSV15   DEPS HITLS_CRYPTO_RSA_PAD)
hitls_define_dependency(HITLS_CRYPTO_RSA_EMSA_PSS       DEPS HITLS_CRYPTO_RSA_PAD HITLS_BSL_PARAMS)
hitls_define_dependency(HITLS_CRYPTO_RSA_BLINDING       DEPS HITLS_CRYPTO_RSA HITLS_CRYPTO_BN_RAND)
hitls_define_dependency(HITLS_CRYPTO_RSA_BSSA
    DEPS HITLS_CRYPTO_RSA HITLS_CRYPTO_RSA_EMSA_PSS HITLS_CRYPTO_RSA_BLINDING
)
hitls_define_dependency(HITLS_CRYPTO_RSA_CHECK
    DEPS HITLS_CRYPTO_RSA HITLS_CRYPTO_BN_RAND HITLS_CRYPTO_BN_PRIME
)
hitls_define_dependency(HITLS_CRYPTO_SP800_STRICT_CHECK DEPS HITLS_CRYPTO_RSA_CHECK)
hitls_define_dependency(HITLS_CRYPTO_DH
    DEPS HITLS_CRYPTO_PKEY
        HITLS_CRYPTO_BN_RAND HITLS_CRYPTO_PKEY_EXCH HITLS_BSL_PARAMS
    CHILDREN HITLS_CRYPTO_DH_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_DH_CHECK           DEPS HITLS_CRYPTO_DH)
hitls_define_dependency(HITLS_CRYPTO_ECC
    DEPS HITLS_CRYPTO_PKEY HITLS_CRYPTO_BN_RAND
    CHILDREN
        HITLS_CRYPTO_CURVE_NISTP192 HITLS_CRYPTO_CURVE_NISTP224
        HITLS_CRYPTO_CURVE_NISTP256 HITLS_CRYPTO_CURVE_NISTP384
        HITLS_CRYPTO_CURVE_NISTP521 HITLS_CRYPTO_CURVE_BP256R1
        HITLS_CRYPTO_CURVE_BP384R1  HITLS_CRYPTO_CURVE_BP512R1
        HITLS_CRYPTO_CURVE_SM2      HITLS_CRYPTO_ECC_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_ECC_CHECK          DEPS HITLS_CRYPTO_ECC)
hitls_define_dependency(HITLS_CRYPTO_CURVE_MONT         DEPS HITLS_CRYPTO_ECC)
hitls_define_dependency(HITLS_CRYPTO_CURVE_MONT_NIST        DEPS HITLS_CRYPTO_CURVE_MONT)
hitls_define_dependency(HITLS_CRYPTO_CURVE_MONT_PRIME       DEPS HITLS_CRYPTO_CURVE_MONT)
hitls_define_dependency(HITLS_CRYPTO_CURVE_BP256R1      DEPS HITLS_CRYPTO_ECC HITLS_CRYPTO_CURVE_MONT_PRIME)
hitls_define_dependency(HITLS_CRYPTO_CURVE_BP384R1      DEPS HITLS_CRYPTO_ECC HITLS_CRYPTO_CURVE_MONT_PRIME)
hitls_define_dependency(HITLS_CRYPTO_CURVE_BP512R1      DEPS HITLS_CRYPTO_ECC HITLS_CRYPTO_CURVE_MONT_PRIME)
hitls_define_dependency(HITLS_CRYPTO_CURVE_NISTP192     DEPS HITLS_CRYPTO_ECC)
hitls_define_dependency(HITLS_CRYPTO_CURVE_NISTP224     DEPS HITLS_CRYPTO_ECC)
hitls_define_dependency(HITLS_CRYPTO_CURVE_NISTP256     DEPS HITLS_CRYPTO_ECC)
hitls_define_dependency(HITLS_CRYPTO_CURVE_NISTP384     DEPS HITLS_CRYPTO_ECC)
hitls_define_dependency(HITLS_CRYPTO_CURVE_NISTP521     DEPS HITLS_CRYPTO_ECC)
hitls_define_dependency(HITLS_CRYPTO_CURVE_SM2          DEPS HITLS_CRYPTO_ECC)
hitls_define_dependency(HITLS_CRYPTO_ECDSA
    DEPS HITLS_CRYPTO_ECC
        HITLS_CRYPTO_PKEY_SIGN HITLS_CRYPTO_MD HITLS_BSL_ASN1 HITLS_BSL_PARAMS
    CHILDREN HITLS_CRYPTO_ECDSA_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_ECDSA_CMP          DEPS HITLS_CRYPTO_ECC_CMP)
hitls_define_dependency(HITLS_CRYPTO_ECDSA_CHECK        DEPS HITLS_CRYPTO_ECDSA HITLS_CRYPTO_ECC_CHECK)
hitls_define_dependency(HITLS_CRYPTO_ECDH
    DEPS HITLS_CRYPTO_ECC HITLS_BSL_PARAMS
    CHILDREN HITLS_CRYPTO_ECDH_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_ECDH_CMP           DEPS HITLS_CRYPTO_ECC_CMP)
hitls_define_dependency(HITLS_CRYPTO_ECDH_CHECK         DEPS HITLS_CRYPTO_ECDH HITLS_CRYPTO_ECC_CHECK)
hitls_define_dependency(HITLS_CRYPTO_SM2
    DEPS HITLS_CRYPTO_ECC
        HITLS_CRYPTO_SM3 HITLS_CRYPTO_CURVE_SM2 HITLS_BSL_ASN1 HITLS_BSL_PARAMS
    CHILDREN HITLS_CRYPTO_SM2_SIGN HITLS_CRYPTO_SM2_CRYPT HITLS_CRYPTO_SM2_EXCH HITLS_CRYPTO_SM2_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_SM2_SIGN
    DEPS HITLS_CRYPTO_SM2 HITLS_CRYPTO_PKEY_SIGN
)
hitls_define_dependency(HITLS_CRYPTO_SM2_CRYPT
    DEPS HITLS_CRYPTO_SM2 HITLS_CRYPTO_PKEY_CRYPT
)
hitls_define_dependency(HITLS_CRYPTO_SM2_EXCH           DEPS HITLS_CRYPTO_SM2 HITLS_CRYPTO_PKEY_EXCH)
hitls_define_dependency(HITLS_CRYPTO_SM2_CMP            DEPS HITLS_CRYPTO_ECC_CMP)
hitls_define_dependency(HITLS_CRYPTO_SM2_CHECK          DEPS HITLS_CRYPTO_SM2 HITLS_CRYPTO_ECC_CHECK)
hitls_define_dependency(HITLS_CRYPTO_SM9
    DEPS HITLS_CRYPTO_PKEY HITLS_CRYPTO_SM3 HITLS_BSL_PARAMS
    CHILDREN HITLS_CRYPTO_SM9_SIGN HITLS_CRYPTO_SM9_CRYPT HITLS_CRYPTO_SM9_EXCH HITLS_CRYPTO_SM9_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_SM9_CRYPT          DEPS HITLS_CRYPTO_SM9 HITLS_CRYPTO_PKEY_CRYPT)
hitls_define_dependency(HITLS_CRYPTO_SM9_EXCH           DEPS HITLS_CRYPTO_SM9 HITLS_CRYPTO_PKEY_EXCH)
hitls_define_dependency(HITLS_CRYPTO_SM9_SIGN           DEPS HITLS_CRYPTO_SM9 HITLS_CRYPTO_PKEY_SIGN)
hitls_define_dependency(HITLS_CRYPTO_SM9_CHECK          DEPS HITLS_CRYPTO_SM9)
hitls_define_dependency(HITLS_CRYPTO_PAILLIER           DEPS HITLS_CRYPTO_PKEY
    HITLS_CRYPTO_PKEY_CRYPT HITLS_CRYPTO_BN_RAND HITLS_CRYPTO_BN_PRIME HITLS_BSL_PARAMS
)
hitls_define_dependency(HITLS_CRYPTO_ELGAMAL
    DEPS HITLS_CRYPTO_PKEY HITLS_CRYPTO_BN_RAND HITLS_CRYPTO_BN_PRIME
)
hitls_define_dependency(HITLS_CRYPTO_XMSS
    DEPS HITLS_CRYPTO_PKEY HITLS_CRYPTO_XMSS_CHECK
        HITLS_CRYPTO_EAL HITLS_CRYPTO_SHA256 HITLS_CRYPTO_SHA512 HITLS_CRYPTO_SHA3 HITLS_BSL_PARAMS
)
hitls_define_dependency(HITLS_CRYPTO_SLH_DSA
    DEPS HITLS_CRYPTO_PKEY
        HITLS_CRYPTO_EAL HITLS_CRYPTO_XMSS HITLS_CRYPTO_PKEY_SIGN HITLS_CRYPTO_HMAC HITLS_CRYPTO_SHA256
        HITLS_CRYPTO_SHA512 HITLS_CRYPTO_SHA3 HITLS_BSL_OBJ_DEFAULT
    CHILDREN HITLS_CRYPTO_SLH_DSA_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_SLH_DSA_CHECK      DEPS HITLS_CRYPTO_SLH_DSA)
hitls_define_dependency(HITLS_CRYPTO_MLKEM
    DEPS HITLS_CRYPTO_PKEY HITLS_CRYPTO_PKEY_KEM HITLS_CRYPTO_SHA3
    CHILDREN HITLS_CRYPTO_MLKEM_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_MLKEM_CHECK        DEPS HITLS_CRYPTO_MLKEM)
hitls_define_dependency(HITLS_CRYPTO_FRODOKEM
    DEPS HITLS_CRYPTO_PKEY HITLS_CRYPTO_PKEY_KEM HITLS_CRYPTO_AES HITLS_CRYPTO_SHA3 HITLS_BSL_PARAMS
)
hitls_define_dependency(HITLS_CRYPTO_MLDSA
    DEPS HITLS_CRYPTO_PKEY
        HITLS_CRYPTO_PKEY_SIGN HITLS_CRYPTO_SHA3 HITLS_BSL_PARAMS HITLS_BSL_OBJ_DEFAULT
    CHILDREN HITLS_CRYPTO_MLDSA_CHECK
)
hitls_define_dependency(HITLS_CRYPTO_MLDSA_CHECK        DEPS HITLS_CRYPTO_MLDSA)
hitls_define_dependency(HITLS_CRYPTO_MCELIECE
    DEPS HITLS_CRYPTO_PKEY HITLS_CRYPTO_PKEY_KEM HITLS_CRYPTO_AES HITLS_CRYPTO_SHA3 HITLS_BSL_PARAMS
)
hitls_define_dependency(HITLS_CRYPTO_HYBRIDKEM          DEPS HITLS_CRYPTO_PKEY
    HITLS_CRYPTO_PKEY_KEM HITLS_CRYPTO_ECDH HITLS_CRYPTO_X25519 HITLS_CRYPTO_MLKEM
)
## Hpke
hitls_define_dependency(HITLS_CRYPTO_HPKE               DEPS HITLS_CRYPTO_PKEY
    HITLS_CRYPTO_CIPHER HITLS_CRYPTO_HKDF HITLS_CRYPTO_DRBG HITLS_CRYPTO_BN_BASIC HITLS_BSL_PARAMS
)
## Provider
hitls_define_dependency(HITLS_CRYPTO_PROVIDER           DEPS HITLS_CRYPTO
    HITLS_BSL_HASH HITLS_BSL_LIST HITLS_BSL_PARAMS HITLS_BSL_SAL_DL HITLS_BSL_SAL_STR
)
hitls_define_dependency(HITLS_CRYPTO_CMVP               DEPS HITLS_CRYPTO_PROVIDER HITLS_CRYPTO_BN)
hitls_define_dependency(HITLS_CRYPTO_CMVP_FIPS          DEPS HITLS_CRYPTO_CMVP)
hitls_define_dependency(HITLS_CRYPTO_CMVP_ISO19790      DEPS HITLS_CRYPTO_CMVP)
hitls_define_dependency(HITLS_CRYPTO_CMVP_SM
    DEPS HITLS_CRYPTO_CMVP HITLS_CRYPTO_KEY_DECODE_CHAIN HITLS_BSL_PEM
)
## Codecs
hitls_define_dependency(HITLS_CRYPTO_CODECS             DEPS HITLS_CRYPTO_PROVIDER)

# Crypto Assembling Dependencies
hitls_define_dependency(HITLS_ASM                       DEPS HITLS_CRYPTO_ASM_CHECK)
hitls_define_dependency(HITLS_CRYPTO_BN_ARMV8           DEPS HITLS_CRYPTO_BN_ASM)
hitls_define_dependency(HITLS_CRYPTO_BN_X8664           DEPS HITLS_CRYPTO_BN_ASM)
hitls_define_dependency(HITLS_CRYPTO_AES_ARMV8          DEPS HITLS_CRYPTO_AES_ASM)
hitls_define_dependency(HITLS_CRYPTO_AES_X8664          DEPS HITLS_CRYPTO_AES_ASM)
hitls_define_dependency(HITLS_CRYPTO_SM4_ARMV8          DEPS HITLS_CRYPTO_SM4_ASM)
hitls_define_dependency(HITLS_CRYPTO_SM4_X8664          DEPS HITLS_CRYPTO_SM4_ASM HITLS_CRYPTO_EALINIT)
hitls_define_dependency(HITLS_CRYPTO_CHACHA20_ASM       DEPS HITLS_CRYPTO_CHACHA20POLY1305_ASM)
hitls_define_dependency(HITLS_CRYPTO_CHACHA20_ARMV8     DEPS HITLS_CRYPTO_CHACHA20_ASM)
hitls_define_dependency(HITLS_CRYPTO_CHACHA20_X8664     DEPS HITLS_CRYPTO_CHACHA20_ASM)
hitls_define_dependency(HITLS_CRYPTO_CHACHA20_X8664_AVX512  DEPS HITLS_CRYPTO_CHACHA20_ASM)
hitls_define_dependency(HITLS_CRYPTO_MODES_ARMV8
    DEPS     HITLS_CRYPTO_MODES_ASM
    CHILDREN HITLS_CRYPTO_GHASH_ARMV8 HITLS_CRYPTO_CHACHA20POLY1305_ARMV8
)
hitls_define_dependency(HITLS_CRYPTO_MODES_X8664
    DEPS     HITLS_CRYPTO_MODES_ASM
    CHILDREN HITLS_CRYPTO_GHASH_X8664 HITLS_CRYPTO_CHACHA20POLY1305_X8664
)
hitls_define_dependency(HITLS_CRYPTO_MODES_X8664_AVX512
    DEPS     HITLS_CRYPTO_MODES_ASM
    CHILDREN HITLS_CRYPTO_GHASH_X8664 HITLS_CRYPTO_CHACHA20POLY1305_X8664_AVX512
)
hitls_define_dependency(HITLS_CRYPTO_GCM_ARMV8          DEPS HITLS_CRYPTO_GHASH_ASM)
hitls_define_dependency(HITLS_CRYPTO_GCM_X8664          DEPS HITLS_CRYPTO_GHASH_ASM)
hitls_define_dependency(HITLS_CRYPTO_CHACHA20POLY1305_X8664 DEPS HITLS_CRYPTO_CHACHA20POLY1305_ASM)
hitls_define_dependency(HITLS_CRYPTO_CHACHA20POLY1305_X8664_AVX512 DEPS HITLS_CRYPTO_CHACHA20POLY1305_ASM)
hitls_define_dependency(HITLS_CRYPTO_MD5_X8664          DEPS HITLS_CRYPTO_MD5_ASM)
hitls_define_dependency(HITLS_CRYPTO_SHA1_ARMV8
    DEPS HITLS_CRYPTO_SHA1_ASM
    DEPS_CHECK HITLS_CRYPTO_EALINIT
)
hitls_define_dependency(HITLS_CRYPTO_SHA1_X8664         DEPS HITLS_CRYPTO_SHA1_ASM)
hitls_define_dependency(HITLS_CRYPTO_SHA2_ARMV8
    DEPS     HITLS_CRYPTO_SHA2_ASM
    DEPS_CHECK HITLS_CRYPTO_EALINIT
    CHILDREN HITLS_CRYPTO_SHA256_ARMV8 HITLS_CRYPTO_SHA512_ARMV8
)
hitls_define_dependency(HITLS_CRYPTO_SHA2_X8664
    DEPS     HITLS_CRYPTO_SHA2_ASM
    CHILDREN HITLS_CRYPTO_SHA256_X8664 HITLS_CRYPTO_SHA512_X8664
)

hitls_define_dependency(HITLS_CRYPTO_SHA256_ARMV8
    DEPS HITLS_CRYPTO_SHA2_ARMV8
    DEPS_CHECK HITLS_CRYPTO_EALINIT
)
hitls_define_dependency(HITLS_CRYPTO_SHA512_ARMV8       DEPS HITLS_CRYPTO_SHA2_ARMV8)
hitls_define_dependency(HITLS_CRYPTO_SHA256_X8664       DEPS HITLS_CRYPTO_SHA2_X8664)
hitls_define_dependency(HITLS_CRYPTO_SHA512_X8664       DEPS HITLS_CRYPTO_SHA2_X8664)
hitls_define_dependency(HITLS_CRYPTO_SHA3_ARMV8         DEPS HITLS_CRYPTO_SHA3_ASM)
hitls_define_dependency(HITLS_CRYPTO_SM3_ARMV8          DEPS HITLS_CRYPTO_SM3_ASM)
hitls_define_dependency(HITLS_CRYPTO_SM3_ARMV7          DEPS HITLS_CRYPTO_SM3_ASM)
hitls_define_dependency(HITLS_CRYPTO_SM3_X8664          DEPS HITLS_CRYPTO_SM3_ASM)
hitls_define_dependency(HITLS_CRYPTO_ECC_ARMV8
    DEPS HITLS_CRYPTO_ECC_ASM
    CHILDREN HITLS_CRYPTO_CURVE_NISTP256_ARMV8 HITLS_CRYPTO_CURVE_NISTP384_ARMV8 HITLS_CRYPTO_CURVE_SM2_ARMV8
)
hitls_define_dependency(HITLS_CRYPTO_ECC_ARMV7          DEPS HITLS_CRYPTO_ECC_ASM)
hitls_define_dependency(HITLS_CRYPTO_ECC_X8664
    DEPS HITLS_CRYPTO_ECC_ASM
    CHILDREN HITLS_CRYPTO_CURVE_NISTP256_X8664 HITLS_CRYPTO_CURVE_NISTP384_X8664 HITLS_CRYPTO_CURVE_SM2_X8664
)
hitls_define_dependency(HITLS_CRYPTO_CURVE_NISTP256_ARMV8 DEPS HITLS_CRYPTO_CURVE_NISTP256_ASM)
hitls_define_dependency(HITLS_CRYPTO_CURVE_NISTP256_X8664 DEPS HITLS_CRYPTO_CURVE_NISTP256_ASM)
hitls_define_dependency(HITLS_CRYPTO_CURVE_NISTP384_ARMV8 DEPS HITLS_CRYPTO_CURVE_NISTP384_ASM)
hitls_define_dependency(HITLS_CRYPTO_CURVE_NISTP384_X8664 DEPS HITLS_CRYPTO_CURVE_NISTP384_ASM)
hitls_define_dependency(HITLS_CRYPTO_CURVE_SM2_ARMV8    DEPS HITLS_CRYPTO_CURVE_SM2_ASM)
hitls_define_dependency(HITLS_CRYPTO_CURVE_SM2_ARMV7    DEPS HITLS_CRYPTO_CURVE_SM2_ASM)
hitls_define_dependency(HITLS_CRYPTO_CURVE_SM2_X8664    DEPS HITLS_CRYPTO_CURVE_SM2_ASM)
hitls_define_dependency(HITLS_CRYPTO_X25519_ARMV8       DEPS HITLS_CRYPTO_X25519_ASM)
hitls_define_dependency(HITLS_CRYPTO_X25519_X8664       DEPS HITLS_CRYPTO_X25519_ASM)
hitls_define_dependency(HITLS_CRYPTO_MLKEM_ARMV8        DEPS HITLS_CRYPTO_MLKEM_ASM)

# PKI Dependencies
hitls_define_dependency(HITLS_PKI
    DEPS HITLS_BSL_SAL HITLS_BSL_LIST HITLS_BSL_ASN1 HITLS_BSL_OBJ_DEFAULT
    CHILDREN HITLS_PKI_X509 HITLS_PKI_CMS HITLS_PKI_PKCS12 HITLS_PKI_INFO
)
## X509
hitls_define_dependency(HITLS_PKI_X509
    DEPS HITLS_PKI
    CHILDREN HITLS_PKI_X509_CRT HITLS_PKI_X509_CSR HITLS_PKI_X509_CRL HITLS_PKI_X509_VFY
)
hitls_define_dependency(HITLS_PKI_X509_CRT
    DEPS HITLS_PKI_X509 HITLS_BSL_LIST HITLS_BSL_OBJ_DEFAULT HITLS_BSL_ASN1
    CHILDREN HITLS_PKI_X509_CRT_GEN HITLS_PKI_X509_CRT_PARSE HITLS_PKI_X509_CRT_AUTH
)
hitls_define_dependency(HITLS_PKI_X509_CRT_GEN          DEPS HITLS_PKI_X509_CRT HITLS_CRYPTO_KEY_ENCODE)
hitls_define_dependency(HITLS_PKI_X509_CRT_PARSE        DEPS HITLS_PKI_X509_CRT HITLS_CRYPTO_KEY_DECODE)
hitls_define_dependency(HITLS_PKI_X509_CRT_AUTH         DEPS HITLS_PKI_X509_CRT)
hitls_define_dependency(HITLS_PKI_X509_CSR
    DEPS HITLS_PKI_X509 HITLS_BSL_LIST HITLS_BSL_OBJ_DEFAULT HITLS_BSL_ASN1
    CHILDREN HITLS_PKI_X509_CSR_GEN HITLS_PKI_X509_CSR_PARSE HITLS_PKI_X509_CSR_ATTR HITLS_PKI_X509_CSR_GET
)
hitls_define_dependency(HITLS_PKI_X509_CSR_GEN          DEPS HITLS_PKI_X509_CSR HITLS_CRYPTO_KEY_ENCODE)
hitls_define_dependency(HITLS_PKI_X509_CSR_PARSE        DEPS HITLS_PKI_X509_CSR HITLS_CRYPTO_KEY_DECODE)
hitls_define_dependency(HITLS_PKI_X509_CSR_ATTR         DEPS HITLS_PKI_X509_CSR)
hitls_define_dependency(HITLS_PKI_X509_CSR_GET          DEPS HITLS_PKI_X509_CSR)
hitls_define_dependency(HITLS_PKI_X509_CRL
    DEPS HITLS_PKI_X509 HITLS_BSL_LIST HITLS_BSL_OBJ_DEFAULT HITLS_BSL_ASN1
    CHILDREN HITLS_PKI_X509_CRL_GEN HITLS_PKI_X509_CRL_PARSE
)
hitls_define_dependency(HITLS_PKI_X509_CRL_GEN          DEPS HITLS_PKI_X509_CRL HITLS_CRYPTO_KEY_ENCODE)
hitls_define_dependency(HITLS_PKI_X509_CRL_PARSE        DEPS HITLS_PKI_X509_CRL HITLS_CRYPTO_KEY_DECODE)
hitls_define_dependency(HITLS_PKI_X509_VFY
    DEPS HITLS_PKI_X509
    CHILDREN
        HITLS_PKI_X509_VFY_DEFAULT HITLS_PKI_X509_VFY_CB
        HITLS_PKI_X509_VFY_LOCATION HITLS_PKI_X509_VFY_IDENTITY
)
hitls_define_dependency(HITLS_PKI_X509_VFY_DEFAULT      DEPS HITLS_PKI_X509_VFY
    HITLS_PKI_X509_CRT_PARSE HITLS_PKI_X509_CRL_PARSE
)
hitls_define_dependency(HITLS_PKI_X509_VFY_CB           DEPS HITLS_PKI_X509_VFY HITLS_PKI_X509_VFY_DEFAULT)
hitls_define_dependency(HITLS_PKI_X509_VFY_LOCATION
    DEPS HITLS_PKI_X509_VFY HITLS_PKI_X509_VFY_DEFAULT HITLS_BSL_SAL_FILE
)
hitls_define_dependency(HITLS_PKI_X509_VFY_IDENTITY     DEPS HITLS_PKI_X509 HITLS_BSL_SAL_IP)
## CMS
hitls_define_dependency(HITLS_PKI_CMS
    DEPS HITLS_PKI HITLS_BSL_ASN1
    CHILDREN HITLS_PKI_CMS_DATA HITLS_PKI_CMS_DIGESTINFO HITLS_PKI_CMS_SIGNEDDATA HITLS_PKI_CMS_ENCRYPTDATA
)
hitls_define_dependency(HITLS_PKI_CMS_DATA              DEPS HITLS_PKI_CMS HITLS_BSL_ASN1)
hitls_define_dependency(HITLS_PKI_CMS_DIGESTINFO        DEPS HITLS_PKI_CMS HITLS_BSL_ASN1)
hitls_define_dependency(HITLS_PKI_CMS_SIGNEDDATA        DEPS HITLS_PKI_CMS HITLS_BSL_ASN1
    HITLS_PKI_X509_CRL_GEN HITLS_PKI_X509_CRL_PARSE # Expand HITLS_PKI_X509_CRL
    HITLS_PKI_X509_CRT_GEN HITLS_PKI_X509_CRT_PARSE HITLS_PKI_X509_CRT_AUTH # Expand HITLS_PKI_X509_CRT
    HITLS_PKI_X509_VFY_DEFAULT
)
hitls_define_dependency(HITLS_PKI_CMS_ENCRYPTDATA       DEPS HITLS_PKI_CMS HITLS_CRYPTO_KEY_EPKI)
## PKCS12
hitls_define_dependency(HITLS_PKI_PKCS12
    DEPS HITLS_PKI HITLS_BSL_ASN1 HITLS_PKI_CMS_DIGESTINFO HITLS_PKI_CMS_DATA HITLS_PKI_CMS_ENCRYPTDATA
    CHILDREN HITLS_PKI_PKCS12_GEN HITLS_PKI_PKCS12_PARSE
)
hitls_define_dependency(HITLS_PKI_PKCS12_GEN            DEPS HITLS_PKI_PKCS12
    HITLS_PKI_X509_CRT_GEN HITLS_PKI_X509_CRT_PARSE HITLS_CRYPTO_KEY_ENCODE HITLS_CRYPTO_KEY_DECODE
    HITLS_PKI_CMS_DIGESTINFO HITLS_PKI_CMS_ENCRYPTDATA HITLS_CRYPTO_KEY_EPKI
)
hitls_define_dependency(HITLS_PKI_PKCS12_PARSE          DEPS HITLS_PKI_PKCS12
    HITLS_PKI_X509_CRT_PARSE HITLS_CRYPTO_KEY_DECODE HITLS_PKI_CMS_SIGNEDDATA HITLS_PKI_CMS_DIGESTINFO
    HITLS_PKI_CMS_ENCRYPTDATA HITLS_CRYPTO_KEY_EPKI
)
## Info/Print
hitls_define_dependency(HITLS_PKI_INFO
    DEPS HITLS_PKI HITLS_BSL_UIO_PLT HITLS_BSL_PRINT
    CHILDREN
        HITLS_PKI_INFO_DN_CONF HITLS_PKI_INFO_DN_HASH
        HITLS_PKI_INFO_CRT HITLS_PKI_INFO_CSR HITLS_PKI_INFO_CRL
)
hitls_define_dependency(HITLS_PKI_INFO_DN_CONF          DEPS HITLS_PKI_INFO)
hitls_define_dependency(HITLS_PKI_INFO_DN_HASH          DEPS HITLS_PKI_INFO)
hitls_define_dependency(HITLS_PKI_INFO_CRT              DEPS HITLS_PKI_INFO HITLS_CRYPTO_KEY_INFO HITLS_PKI_X509_CRT)
hitls_define_dependency(HITLS_PKI_INFO_CSR              DEPS HITLS_PKI_INFO HITLS_CRYPTO_KEY_INFO HITLS_PKI_X509_CSR)
hitls_define_dependency(HITLS_PKI_INFO_CRL              DEPS HITLS_PKI_INFO HITLS_CRYPTO_KEY_INFO HITLS_PKI_X509_CRL)

# TLS Dependencies
hitls_define_dependency(HITLS_TLS
    DEPS HITLS_BSL_SAL HITLS_BSL_HASH HITLS_BSL_LIST HITLS_BSL_UIO_PLT
    CHILDREN
        HITLS_TLS_PROTO_VERSION HITLS_TLS_HOST
        HITLS_TLS_CALLBACK      HITLS_TLS_FEATURE
        HITLS_TLS_PROTO         HITLS_TLS_CONFIG
        HITLS_TLS_CONNECTION    
        HITLS_TLS_SUITE_CIPHER  HITLS_TLS_SUITE_KX
        HITLS_TLS_SUITE_AUTH    HITLS_TLS_MAINTAIN
)
## Proto Version
hitls_define_dependency(HITLS_TLS_PROTO_VERSION
    DEPS HITLS_TLS
    CHILDREN
        HITLS_TLS_PROTO_TLS12  HITLS_TLS_PROTO_TLS13
        HITLS_TLS_PROTO_TLCP11 HITLS_TLS_PROTO_DTLCP11 HITLS_TLS_PROTO_DTLS12
)
hitls_define_dependency(HITLS_TLS_PROTO_TLS12
    DEPS HITLS_TLS_PROTO_VERSION HITLS_TLS_PROTO_TLS HITLS_TLS_PROTO_TLS_BASIC
)
hitls_define_dependency(HITLS_TLS_PROTO_TLS13
    DEPS HITLS_TLS_PROTO_VERSION HITLS_TLS_PROTO_TLS HITLS_TLS_EXTENSION_COOKIE
)
hitls_define_dependency(HITLS_TLS_PROTO_TLCP11          DEPS HITLS_TLS_PROTO_VERSION
    HITLS_TLS_PROTO_TLS HITLS_TLS_PROTO_TLS_BASIC HITLS_TLS_FEATURE_CERT_MODE_CLIENT_VERIFY
)
hitls_define_dependency(HITLS_TLS_PROTO_DTLS12
    DEPS HITLS_TLS_PROTO_VERSION HITLS_TLS_PROTO_DTLS HITLS_TLS_EXTENSION_COOKIE
)
hitls_define_dependency(HITLS_TLS_PROTO_DTLCP11
    DEPS HITLS_TLS_PROTO_VERSION HITLS_TLS_PROTO_DTLS12 HITLS_TLS_PROTO_TLCP11
)

## Host
hitls_define_dependency(HITLS_TLS_HOST
    DEPS HITLS_TLS
    CHILDREN HITLS_TLS_HOST_SERVER HITLS_TLS_HOST_CLIENT
)
hitls_define_dependency(HITLS_TLS_HOST_CLIENT           DEPS HITLS_TLS_HOST)
hitls_define_dependency(HITLS_TLS_HOST_SERVER           DEPS HITLS_TLS_HOST)

## Callback / Provider
hitls_define_dependency(HITLS_TLS_CALLBACK
    DEPS HITLS_TLS
    CHILDREN HITLS_TLS_FEATURE_PROVIDER HITLS_TLS_CALLBACK_SAL HITLS_TLS_CALLBACK_CERT HITLS_TLS_CALLBACK_CRYPT
)
hitls_define_dependency(HITLS_TLS_FEATURE_PROVIDER
    DEPS HITLS_TLS_CALLBACK HITLS_BSL_HASH
    DEPS_CHECK HITLS_CRYPTO_PROVIDER
    CHILDREN HITLS_TLS_FEATURE_PROVIDER_HARD_CODING HITLS_TLS_FEATURE_PROVIDER_DYNAMIC
)
hitls_define_dependency(HITLS_TLS_FEATURE_PROVIDER_HARD_CODING   DEPS HITLS_TLS_FEATURE_PROVIDER)
hitls_define_dependency(HITLS_TLS_FEATURE_PROVIDER_DYNAMIC       DEPS HITLS_TLS_FEATURE_PROVIDER)
hitls_define_dependency(HITLS_TLS_CALLBACK_SAL                   DEPS HITLS_TLS_CALLBACK)
hitls_define_dependency(HITLS_TLS_CALLBACK_CERT                  DEPS HITLS_TLS_CALLBACK_SAL)
hitls_define_dependency(HITLS_TLS_CALLBACK_CRYPT                 DEPS HITLS_TLS_CALLBACK_SAL HITLS_BSL_PARAMS)

## Feature
hitls_define_dependency(HITLS_TLS_FEATURE
    DEPS HITLS_TLS
    CHILDREN
        HITLS_TLS_FEATURE_RENEGOTIATION    HITLS_TLS_FEATURE_ALPN
        HITLS_TLS_FEATURE_SNI              HITLS_TLS_FEATURE_PHA
        HITLS_TLS_FEATURE_PSK              HITLS_TLS_FEATURE_SECURITY
        HITLS_TLS_FEATURE_INDICATOR        HITLS_TLS_FEATURE_SESSION
        HITLS_TLS_FEATURE_KEY_UPDATE       HITLS_TLS_FEATURE_MODE
        HITLS_TLS_FEATURE_KEM              HITLS_TLS_FEATURE_FLIGHT
        HITLS_TLS_FEATURE_CERT_MODE        HITLS_TLS_FEATURE_CLIENT_HELLO_CB
        HITLS_TLS_FEATURE_CERT_CB          HITLS_TLS_FEATURE_MAX_SEND_FRAGMENT
        HITLS_TLS_FEATURE_CUSTOM_EXTENSION HITLS_TLS_FEATURE_ANTI_REPLAY
        HITLS_TLS_FEATURE_EXTENDED_MASTER_SECRET HITLS_TLS_FEATURE_REC_INBUFFER_SIZE
        HITLS_TLS_FEATURE_CERTIFICATE_AUTHORITIES HITLS_TLS_FEATURE_SM_TLS13
        HITLS_TLS_FEATURE_MTU_QUERY        HITLS_TLS_FEATURE_EXPORT_KEY_MATERIAL
        HITLS_TLS_FEATURE_RECORD_SIZE_LIMIT HITLS_TLS_FEATURE_DEFAULT_COOKIE
)
hitls_define_dependency(HITLS_TLS_FEATURE_RENEGOTIATION     DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_ALPN              DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_SNI
    DEPS HITLS_TLS_FEATURE
    DEPS_CHECK HITLS_TLS_FEATURE_SESSION
)
hitls_define_dependency(HITLS_TLS_FEATURE_PHA               DEPS HITLS_TLS_FEATURE
    DEPS_CHECK HITLS_TLS_PROTO_TLS13
)
hitls_define_dependency(HITLS_TLS_FEATURE_PSK               DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_SECURITY          DEPS HITLS_TLS_FEATURE HITLS_TLS_CONFIG_CIPHER_SUITE)
hitls_define_dependency(HITLS_TLS_FEATURE_INDICATOR         DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_SESSION
    DEPS HITLS_TLS_FEATURE
        HITLS_TLS_FEATURE_EXTENDED_MASTER_SECRET HITLS_TLS_PROTO_CLOSE_STATE
    CHILDREN
        HITLS_TLS_FEATURE_SESSION_TICKET HITLS_TLS_FEATURE_SESSION_ID
        HITLS_TLS_FEATURE_SESSION_CACHE_CB HITLS_TLS_FEATURE_SESSION_CUSTOM_TICKET
)
hitls_define_dependency(HITLS_TLS_FEATURE_SESSION_TICKET    DEPS HITLS_TLS_FEATURE_SESSION HITLS_BSL_TLV)
hitls_define_dependency(HITLS_TLS_FEATURE_SESSION_ID        DEPS HITLS_TLS_FEATURE_SESSION)
hitls_define_dependency(HITLS_TLS_FEATURE_SESSION_CACHE_CB
    DEPS HITLS_TLS_FEATURE_SESSION HITLS_TLS_FEATURE_SESSION_TICKET HITLS_TLS_FEATURE_SESSION_ID
)
hitls_define_dependency(HITLS_TLS_FEATURE_SESSION_CUSTOM_TICKET
    DEPS HITLS_TLS_FEATURE_SESSION HITLS_TLS_FEATURE_SESSION_TICKET HITLS_TLS_FEATURE_SESSION_ID
)
hitls_define_dependency(HITLS_TLS_FEATURE_EXPORT_KEY_MATERIAL       DEPS HITLS_TLS_FEATURE_SESSION)
hitls_define_dependency(HITLS_TLS_FEATURE_MODE
    DEPS HITLS_TLS_FEATURE
    CHILDREN
        HITLS_TLS_FEATURE_MODE_FALL_BACK_SCSV
        HITLS_TLS_FEATURE_MODE_AUTO_RETRY
        HITLS_TLS_FEATURE_MODE_ACCEPT_MOVING_WRITE_BUFFER
        HITLS_TLS_FEATURE_MODE_RELEASE_BUFFERS
)
hitls_define_dependency(HITLS_TLS_FEATURE_MODE_FALL_BACK_SCSV       DEPS HITLS_TLS_FEATURE_MODE)
hitls_define_dependency(HITLS_TLS_FEATURE_MODE_AUTO_RETRY           DEPS HITLS_TLS_FEATURE_MODE)
hitls_define_dependency(HITLS_TLS_FEATURE_MODE_ACCEPT_MOVING_WRITE_BUFFER   DEPS HITLS_TLS_FEATURE_MODE)
hitls_define_dependency(HITLS_TLS_FEATURE_MODE_RELEASE_BUFFERS      DEPS HITLS_TLS_FEATURE_MODE)
hitls_define_dependency(HITLS_TLS_FEATURE_KEY_UPDATE        DEPS HITLS_TLS_FEATURE
    DEPS_CHECK HITLS_TLS_PROTO_TLS13
)
hitls_define_dependency(HITLS_TLS_FEATURE_FLIGHT                    DEPS HITLS_TLS_FEATURE HITLS_BSL_UIO_BUFFER)
hitls_define_dependency(HITLS_TLS_FEATURE_CERT_MODE
    DEPS HITLS_TLS_FEATURE
    CHILDREN HITLS_TLS_FEATURE_CERT_MODE_VERIFY_PEER HITLS_TLS_FEATURE_CERT_MODE_CLIENT_VERIFY
)
hitls_define_dependency(HITLS_TLS_FEATURE_CERT_MODE_CLIENT_VERIFY   DEPS HITLS_TLS_FEATURE_CERT_MODE)
hitls_define_dependency(HITLS_TLS_FEATURE_CERT_MODE_VERIFY_PEER     DEPS HITLS_TLS_FEATURE_CERT_MODE)
hitls_define_dependency(HITLS_TLS_FEATURE_ANTI_REPLAY               DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_EXTENDED_MASTER_SECRET    DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_RECORD_SIZE_LIMIT         DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_KEM                       DEPS HITLS_TLS_FEATURE HITLS_CRYPTO_PKEY_KEM)
hitls_define_dependency(HITLS_TLS_FEATURE_CLIENT_HELLO_CB           DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_CERT_CB                   DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_MAX_SEND_FRAGMENT         DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_REC_INBUFFER_SIZE         DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_CUSTOM_EXTENSION          DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_CERTIFICATE_AUTHORITIES   DEPS HITLS_TLS_FEATURE HITLS_PKI_X509_CRT_AUTH)
hitls_define_dependency(HITLS_TLS_FEATURE_MTU_QUERY                 DEPS HITLS_TLS_FEATURE)
hitls_define_dependency(HITLS_TLS_FEATURE_SM_TLS13
    DEPS HITLS_TLS_FEATURE HITLS_TLS_CONFIG_KEY_USAGE
    DEPS_CHECK HITLS_TLS_PROTO_TLS13
    CHILDREN HITLS_TLS_SUITE_SM4_GCM_SM3 HITLS_TLS_SUITE_SM4_CCM_SM3
)
hitls_define_dependency(HITLS_TLS_FEATURE_ETM                       DEPS_CHECK HITLS_TLS_SUITE_CIPHER_CBC)

## Proto
hitls_define_dependency(HITLS_TLS_PROTO
    DEPS HITLS_TLS HITLS_CRYPTO_EAL HITLS_BSL_LIST HITLS_TLS_FEATURE_EXTENDED_MASTER_SECRET
    CHILDREN HITLS_TLS_PROTO_DFX HITLS_TLS_PROTO_CLOSE_STATE
)
hitls_define_dependency(HITLS_TLS_PROTO_CLOSE_STATE         DEPS HITLS_TLS_PROTO)
hitls_define_dependency(HITLS_TLS_PROTO_DFX
    DEPS HITLS_TLS_PROTO
    CHILDREN
        HITLS_TLS_PROTO_DFX_CHECK HITLS_TLS_PROTO_DFX_INFO
        HITLS_TLS_PROTO_DFX_ALERT_NUMBER HITLS_TLS_PROTO_DFX_SERVER_PREFER
)
hitls_define_dependency(HITLS_TLS_PROTO_DFX_CHECK           DEPS HITLS_TLS_PROTO_DFX)
hitls_define_dependency(HITLS_TLS_PROTO_DFX_INFO            DEPS HITLS_TLS_PROTO_DFX)
hitls_define_dependency(HITLS_TLS_PROTO_DFX_ALERT_NUMBER    DEPS HITLS_TLS_PROTO_DFX)
hitls_define_dependency(HITLS_TLS_PROTO_DFX_SERVER_PREFER   DEPS HITLS_TLS_PROTO_DFX)

## Config
hitls_define_dependency(HITLS_TLS_CONFIG
    DEPS HITLS_TLS
    CHILDREN
        HITLS_TLS_CONFIG_MANUAL_DH    HITLS_TLS_CONFIG_CERT
        HITLS_TLS_CONFIG_KEY_USAGE    HITLS_TLS_CONFIG_STATE
        HITLS_TLS_CONFIG_RECORD_PADDING HITLS_TLS_CONFIG_USER_DATA
        HITLS_TLS_CONFIG_CIPHER_SUITE HITLS_TLS_CONFIG_VERSION
)
hitls_define_dependency(HITLS_TLS_CONFIG_MANUAL_DH          DEPS HITLS_TLS_CONFIG)
hitls_define_dependency(HITLS_TLS_CONFIG_CERT
    DEPS HITLS_TLS_CONFIG
    CHILDREN
        HITLS_TLS_CONFIG_CERT_LOAD_FILE    HITLS_TLS_CONFIG_CERT_CALLBACK
        HITLS_TLS_CONFIG_CERT_BUILD_CHAIN  HITLS_TLS_CONFIG_CERT_VERIFY_LOCATION
        HITLS_TLS_CONFIG_CERT_CRL
)
hitls_define_dependency(HITLS_TLS_CONFIG_CERT_LOAD_FILE     DEPS HITLS_TLS_CONFIG_CERT)
hitls_define_dependency(HITLS_TLS_CONFIG_CERT_CALLBACK      DEPS HITLS_TLS_CONFIG_CERT HITLS_PKI_X509_VFY_CB)
hitls_define_dependency(HITLS_TLS_CONFIG_CERT_BUILD_CHAIN   DEPS HITLS_TLS_CONFIG_CERT)
hitls_define_dependency(HITLS_TLS_CONFIG_CERT_VERIFY_LOCATION DEPS HITLS_TLS_CONFIG_CERT HITLS_BSL_SAL_FILE)
hitls_define_dependency(HITLS_TLS_CONFIG_CERT_CRL           DEPS HITLS_TLS_CONFIG_CERT)
hitls_define_dependency(HITLS_TLS_CONFIG_KEY_USAGE          DEPS HITLS_TLS_CONFIG)
hitls_define_dependency(HITLS_TLS_CONFIG_STATE              DEPS HITLS_TLS_CONFIG)
hitls_define_dependency(HITLS_TLS_CONFIG_RECORD_PADDING     DEPS HITLS_TLS_CONFIG)
hitls_define_dependency(HITLS_TLS_CONFIG_USER_DATA          DEPS HITLS_TLS_CONFIG)
hitls_define_dependency(HITLS_TLS_CONFIG_CIPHER_SUITE       DEPS HITLS_TLS_CONFIG)
hitls_define_dependency(HITLS_TLS_CONFIG_VERSION            DEPS HITLS_TLS_CONFIG)

## Connection
hitls_define_dependency(HITLS_TLS_CONNECTION
    DEPS HITLS_TLS
    CHILDREN HITLS_TLS_CONNECTION_INFO_NEGOTIATION
)
hitls_define_dependency(HITLS_TLS_CONNECTION_INFO_NEGOTIATION   DEPS HITLS_TLS_CONNECTION)

## Cipher Suites (TLS 1.3)
hitls_define_dependency(HITLS_TLS_SUITE
    DEPS HITLS_TLS
    CHILDREN
        HITLS_TLS_SUITE_AES_128_GCM_SHA256                       HITLS_TLS_SUITE_AES_256_GCM_SHA384
        HITLS_TLS_SUITE_CHACHA20_POLY1305_SHA256                 HITLS_TLS_SUITE_AES_128_CCM_SHA256
        HITLS_TLS_SUITE_AES_128_CCM_8_SHA256                     HITLS_TLS_SUITE_RSA_WITH_AES_128_CBC_SHA
        HITLS_TLS_SUITE_RSA_WITH_AES_256_CBC_SHA                 HITLS_TLS_SUITE_RSA_WITH_AES_128_CBC_SHA256
        HITLS_TLS_SUITE_RSA_WITH_AES_256_CBC_SHA256              HITLS_TLS_SUITE_RSA_WITH_AES_128_GCM_SHA256
        HITLS_TLS_SUITE_RSA_WITH_AES_256_GCM_SHA384              HITLS_TLS_SUITE_RSA_WITH_AES_128_CCM
        HITLS_TLS_SUITE_RSA_WITH_AES_128_CCM_8                   HITLS_TLS_SUITE_RSA_WITH_AES_256_CCM
        HITLS_TLS_SUITE_RSA_WITH_AES_256_CCM_8                   HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_GCM_SHA256
        HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_GCM_SHA384          HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_CBC_SHA
        HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_CBC_SHA             HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_CBC_SHA256
        HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_CBC_SHA256          HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_CCM
        HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_CCM                 HITLS_TLS_SUITE_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        HITLS_TLS_SUITE_DHE_DSS_WITH_AES_128_GCM_SHA256          HITLS_TLS_SUITE_DHE_DSS_WITH_AES_256_GCM_SHA384
        HITLS_TLS_SUITE_DHE_DSS_WITH_AES_128_CBC_SHA             HITLS_TLS_SUITE_DHE_DSS_WITH_AES_256_CBC_SHA
        HITLS_TLS_SUITE_DHE_DSS_WITH_AES_128_CBC_SHA256          HITLS_TLS_SUITE_DHE_DSS_WITH_AES_256_CBC_SHA256
        HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_CBC_SHA         HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
        HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256      HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
        HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256      HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_CCM             HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_CCM
        HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256  HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_128_CBC_SHA
        HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_256_CBC_SHA           HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_256_CBC_SHA384        HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_256_GCM_SHA384        HITLS_TLS_SUITE_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        HITLS_TLS_SUITE_DH_ANON_WITH_AES_128_CBC_SHA             HITLS_TLS_SUITE_DH_ANON_WITH_AES_256_CBC_SHA
        HITLS_TLS_SUITE_DH_ANON_WITH_AES_128_CBC_SHA256          HITLS_TLS_SUITE_DH_ANON_WITH_AES_256_CBC_SHA256
        HITLS_TLS_SUITE_DH_ANON_WITH_AES_128_GCM_SHA256          HITLS_TLS_SUITE_DH_ANON_WITH_AES_256_GCM_SHA384
        HITLS_TLS_SUITE_ECDH_ANON_WITH_AES_128_CBC_SHA           HITLS_TLS_SUITE_ECDH_ANON_WITH_AES_256_CBC_SHA
        HITLS_TLS_SUITE_PSK_WITH_AES_128_CBC_SHA                 HITLS_TLS_SUITE_PSK_WITH_AES_256_CBC_SHA
        HITLS_TLS_SUITE_PSK_WITH_AES_128_CBC_SHA256              HITLS_TLS_SUITE_PSK_WITH_AES_256_CBC_SHA384
        HITLS_TLS_SUITE_PSK_WITH_AES_128_GCM_SHA256              HITLS_TLS_SUITE_PSK_WITH_AES_256_GCM_SHA384
        HITLS_TLS_SUITE_PSK_WITH_AES_256_CCM                     HITLS_TLS_SUITE_PSK_WITH_CHACHA20_POLY1305_SHA256
        HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_CBC_SHA             HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_CBC_SHA
        HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_CBC_SHA256          HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_CBC_SHA384
        HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_GCM_SHA256          HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_GCM_SHA384
        HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_CCM                 HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_CCM
        HITLS_TLS_SUITE_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256    HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA
        HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA             HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA256
        HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA384          HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_GCM_SHA256
        HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_GCM_SHA384          HITLS_TLS_SUITE_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256
        HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_CBC_SHA           HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_256_CBC_SHA
        HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_CBC_SHA256        HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_256_CBC_SHA384
        HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_GCM_SHA256        HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_256_GCM_SHA384
        HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_CCM_SHA256        HITLS_TLS_SUITE_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256
        HITLS_TLS_SUITE_ECDHE_SM4_CBC_SM3                        HITLS_TLS_SUITE_ECC_SM4_CBC_SM3
        HITLS_TLS_SUITE_ECDHE_SM4_GCM_SM3                        HITLS_TLS_SUITE_ECC_SM4_GCM_SM3
        HITLS_TLS_SUITE_SM4_GCM_SM3                              HITLS_TLS_SUITE_SM4_CCM_SM3
)

hitls_define_dependency(HITLS_TLS_SUITE_AES_128_GCM_SHA256          DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_AES_256_GCM_SHA384          DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_CHACHA20_POLY1305_SHA256    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CHACHA20POLY1305 HITLS_CRYPTO_CHACHA20 HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_AES_128_CCM_SHA256          DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_AES_128_CCM_8_SHA256        DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH
)
## Cipher Suites (RSA)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_WITH_AES_128_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_WITH_AES_256_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_WITH_AES_128_CBC_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_WITH_AES_256_CBC_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_WITH_AES_128_GCM_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_WITH_AES_256_GCM_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_WITH_AES_128_CCM        DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_WITH_AES_128_CCM_8      DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_WITH_AES_256_CCM        DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_WITH_AES_256_CCM_8      DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
## Cipher Suites (DHE-RSA)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_GCM_SHA256  DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_GCM_SHA384  DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_CBC_SHA     DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_CBC_SHA     DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_CBC_SHA256  DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_CBC_SHA256  DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_CCM         DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_CCM         DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CHACHA20POLY1305 HITLS_CRYPTO_CHACHA20 HITLS_CRYPTO_RSA HITLS_CRYPTO_DH
)
## Cipher Suites (DHE-DSS)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_128_GCM_SHA256  DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_DSS
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_DSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_256_GCM_SHA384  DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_DSS
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_DSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_128_CBC_SHA     DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_DSS
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_256_CBC_SHA     DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_DSS
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_128_CBC_SHA256  DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_DSS
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DSA HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_256_CBC_SHA256  DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_DSS
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DSA HITLS_CRYPTO_DH
)
## Cipher Suites (ECDHE-ECDSA)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_ECDSA
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH HITLS_CRYPTO_ECDSA
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_ECDSA
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH HITLS_CRYPTO_ECDSA
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_ECDSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH HITLS_CRYPTO_ECDSA
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_ECDSA
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH HITLS_CRYPTO_ECDSA
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_ECDSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH HITLS_CRYPTO_ECDSA
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_ECDSA
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH HITLS_CRYPTO_ECDSA
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_CCM        DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_ECDSA
    HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH HITLS_CRYPTO_ECDSA
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_CCM        DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_ECDSA
    HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH HITLS_CRYPTO_ECDSA
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_ECDSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CHACHA20POLY1305 HITLS_CRYPTO_CHACHA20 HITLS_CRYPTO_ECDH HITLS_CRYPTO_ECDSA
)
## Cipher Suites (ECDHE-RSA)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_128_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_256_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_128_CBC_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_256_CBC_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_128_GCM_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_256_GCM_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_RSA
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CHACHA20POLY1305 HITLS_CRYPTO_CHACHA20 HITLS_CRYPTO_RSA
        HITLS_CRYPTO_ECDH
)
## Cipher Suites (DH-ANON / ECDH-ANON)
hitls_define_dependency(HITLS_TLS_SUITE_DH_ANON_WITH_AES_128_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DH_ANON_WITH_AES_256_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DH_ANON_WITH_AES_128_CBC_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DH_ANON_WITH_AES_256_CBC_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DH_ANON_WITH_AES_128_GCM_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DH_ANON_WITH_AES_256_GCM_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDH_ANON_WITH_AES_128_CBC_SHA  DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DH HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDH_ANON_WITH_AES_256_CBC_SHA  DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DH HITLS_CRYPTO_ECDH
)
## Cipher Suites (PSK)
hitls_define_dependency(HITLS_TLS_SUITE_PSK_WITH_AES_128_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES
)
hitls_define_dependency(HITLS_TLS_SUITE_PSK_WITH_AES_256_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES
)
hitls_define_dependency(HITLS_TLS_SUITE_PSK_WITH_AES_128_CBC_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES
)
hitls_define_dependency(HITLS_TLS_SUITE_PSK_WITH_AES_256_CBC_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES
)
hitls_define_dependency(HITLS_TLS_SUITE_PSK_WITH_AES_128_GCM_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES
)
hitls_define_dependency(HITLS_TLS_SUITE_PSK_WITH_AES_256_GCM_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES
)
hitls_define_dependency(HITLS_TLS_SUITE_PSK_WITH_AES_256_CCM        DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_CCM HITLS_CRYPTO_AES
)
hitls_define_dependency(HITLS_TLS_SUITE_PSK_WITH_CHACHA20_POLY1305_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CHACHA20POLY1305 HITLS_CRYPTO_CHACHA20
)
## Cipher Suites (DHE-PSK)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_CBC_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_CBC_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_GCM_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_GCM_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_CCM        DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_CCM        DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_DH
)
hitls_define_dependency(HITLS_TLS_SUITE_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CHACHA20POLY1305 HITLS_CRYPTO_CHACHA20 HITLS_CRYPTO_DH
)
## Cipher Suites (RSA-PSK)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_GCM_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_GCM_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_RSA HITLS_TLS_SUITE_AUTH_RSA HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CHACHA20POLY1305 HITLS_CRYPTO_CHACHA20 HITLS_CRYPTO_RSA
)
## Cipher Suites (ECDHE-PSK)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_256_CBC_SHA    DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA1 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_CBC_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_256_CBC_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_CBC HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_GCM_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_256_GCM_SHA384 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA384 HITLS_CRYPTO_GCM HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_CCM_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CCM HITLS_CRYPTO_AES HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_PSK
    HITLS_CRYPTO_SHA256 HITLS_CRYPTO_CHACHA20POLY1305 HITLS_CRYPTO_CHACHA20 HITLS_CRYPTO_ECDH
)
## Cipher Suites (SM)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_SM4_CBC_SM3   DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_SM2
    HITLS_CRYPTO_SM3 HITLS_CRYPTO_CBC HITLS_CRYPTO_SM4 HITLS_CRYPTO_SM2 HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECC_SM4_CBC_SM3     DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_CBC HITLS_TLS_SUITE_AUTH_SM2
    HITLS_CRYPTO_SM3 HITLS_CRYPTO_CBC HITLS_CRYPTO_SM4 HITLS_CRYPTO_SM2
)
hitls_define_dependency(HITLS_TLS_SUITE_ECDHE_SM4_GCM_SM3   DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_AUTH_SM2
    HITLS_CRYPTO_SM3 HITLS_CRYPTO_GCM HITLS_CRYPTO_SM4 HITLS_CRYPTO_SM2 HITLS_CRYPTO_ECDH
)
hitls_define_dependency(HITLS_TLS_SUITE_ECC_SM4_GCM_SM3     DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_AUTH_SM2
    HITLS_CRYPTO_SM3 HITLS_CRYPTO_GCM HITLS_CRYPTO_SM4 HITLS_CRYPTO_SM2
)
hitls_define_dependency(HITLS_TLS_SUITE_SM4_GCM_SM3         DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_AUTH_SM2
    HITLS_CRYPTO_SM3 HITLS_CRYPTO_GCM HITLS_CRYPTO_SM4 HITLS_CRYPTO_SM2
)
hitls_define_dependency(HITLS_TLS_SUITE_SM4_CCM_SM3         DEPS HITLS_TLS_SUITE
    HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_AUTH_SM2
    HITLS_CRYPTO_SM3 HITLS_CRYPTO_CCM HITLS_CRYPTO_SM4 HITLS_CRYPTO_SM2
)

## Suite Cipher type
hitls_define_dependency(HITLS_TLS_SUITE_CIPHER
    DEPS HITLS_TLS
    CHILDREN HITLS_TLS_SUITE_CIPHER_AEAD HITLS_TLS_SUITE_CIPHER_CBC
)
hitls_define_dependency(HITLS_TLS_SUITE_CIPHER_AEAD         DEPS HITLS_TLS_SUITE_CIPHER)
hitls_define_dependency(HITLS_TLS_SUITE_CIPHER_CBC          DEPS HITLS_TLS_SUITE_CIPHER
    HITLS_TLS_FEATURE_ETM HITLS_TLS_CALLBACK_CRYPT_HMAC_PRIMITIVES
)

## Suite Key Exchange
hitls_define_dependency(HITLS_TLS_SUITE_KX
    DEPS HITLS_TLS
    CHILDREN HITLS_TLS_SUITE_KX_ECDHE HITLS_TLS_SUITE_KX_DHE HITLS_TLS_SUITE_KX_RSA
)
hitls_define_dependency(HITLS_TLS_SUITE_KX_ECDHE            DEPS HITLS_TLS_SUITE_KX)
hitls_define_dependency(HITLS_TLS_SUITE_KX_DHE              DEPS HITLS_TLS_SUITE_KX)
hitls_define_dependency(HITLS_TLS_SUITE_KX_RSA              DEPS HITLS_TLS_SUITE_KX)

## Suite Authentication
hitls_define_dependency(HITLS_TLS_SUITE_AUTH
    DEPS HITLS_TLS
    CHILDREN
        HITLS_TLS_SUITE_AUTH_RSA HITLS_TLS_SUITE_AUTH_ECDSA
        HITLS_TLS_SUITE_AUTH_DSS HITLS_TLS_SUITE_AUTH_PSK
        HITLS_TLS_SUITE_AUTH_SM2
)
hitls_define_dependency(HITLS_TLS_SUITE_AUTH_RSA            DEPS HITLS_TLS_SUITE_AUTH)
hitls_define_dependency(HITLS_TLS_SUITE_AUTH_ECDSA          DEPS HITLS_TLS_SUITE_AUTH)
hitls_define_dependency(HITLS_TLS_SUITE_AUTH_DSS            DEPS HITLS_TLS_SUITE_AUTH)
hitls_define_dependency(HITLS_TLS_SUITE_AUTH_PSK            DEPS HITLS_TLS_SUITE_AUTH)
hitls_define_dependency(HITLS_TLS_SUITE_AUTH_SM2            DEPS HITLS_TLS_SUITE_AUTH)

## Maintain
hitls_define_dependency(HITLS_TLS_MAINTAIN
    DEPS HITLS_TLS HITLS_BSL_LOG HITLS_BSL_ERR
    CHILDREN HITLS_TLS_MAINTAIN_KEYLOG
)
hitls_define_dependency(HITLS_TLS_MAINTAIN_KEYLOG           DEPS HITLS_TLS_MAINTAIN)

# AUTH Dependencies
hitls_define_dependency(HITLS_AUTH
    DEPS HITLS_BSL_SAL
    CHILDREN HITLS_AUTH_PRIVPASS_TOKEN HITLS_AUTH_OTP HITLS_AUTH_PAKE
)
## PrivPass Token
hitls_define_dependency(HITLS_AUTH_PRIVPASS_TOKEN       DEPS HITLS_AUTH HITLS_BSL_PARAMS)
## OTP
hitls_define_dependency(HITLS_AUTH_OTP                  DEPS HITLS_AUTH HITLS_BSL_PARAMS)
## PAKE
hitls_define_dependency(HITLS_AUTH_PAKE
    DEPS HITLS_AUTH
    CHILDREN HITLS_AUTH_PAKE_CORE HITLS_AUTH_SPAKE2PLUS
)
hitls_define_dependency(HITLS_AUTH_PAKE_CORE            DEPS HITLS_AUTH_PAKE)
hitls_define_dependency(HITLS_AUTH_SPAKE2PLUS           DEPS HITLS_AUTH_PAKE_CORE)


# Drive TLS Suites based on the selected KX/Auth/Cipher combinations.
macro(hitls_tls_suites_derive)
    # Aead Cipher
    if(HITLS_TLS_SUITE_CIPHER_AEAD)
        # ECDHE key exchange
        if(HITLS_TLS_SUITE_KX_ECDHE)
            if((HITLS_TLS_SUITE_AUTH_RSA OR HITLS_TLS_SUITE_AUTH_ECDSA OR HITLS_TLS_SUITE_AUTH_PSK) AND
                HITLS_TLS_PROTO_TLS13)
                hitls_feature_local_enable(HITLS_TLS_SUITE_AES_128_GCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_AES_256_GCM_SHA384)
                hitls_feature_local_enable(HITLS_TLS_SUITE_CHACHA20_POLY1305_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_AES_128_CCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_AES_128_CCM_8_SHA256)
            endif()
            # RSA authentication
            if(HITLS_TLS_SUITE_AUTH_RSA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_128_GCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_256_GCM_SHA384)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256)
            endif()
            # ECDSA authentication
            if(HITLS_TLS_SUITE_AUTH_ECDSA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_CCM)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_CCM)
            endif()
            # PSK authentication
            if(HITLS_TLS_SUITE_AUTH_PSK)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_CCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_GCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_256_GCM_SHA384)
            endif()
            # SM2 authentication
            if(HITLS_TLS_SUITE_AUTH_SM2)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_SM4_GCM_SM3)
            endif()
        endif()
        # DHE key exchange
        if(HITLS_TLS_SUITE_KX_DHE)
            # RSA authentication
            if(HITLS_TLS_SUITE_AUTH_RSA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_GCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_GCM_SHA384)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_CCM)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_CCM)
            endif()
            # DSS authentication
            if(HITLS_TLS_SUITE_AUTH_DSS)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_128_GCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_256_GCM_SHA384)
            endif()
            # PSK authentication
            if(HITLS_TLS_SUITE_AUTH_PSK)
                if(HITLS_TLS_PROTO_TLS13)
                    hitls_feature_local_enable(HITLS_TLS_SUITE_AES_128_GCM_SHA256)
                    hitls_feature_local_enable(HITLS_TLS_SUITE_AES_256_GCM_SHA384)
                    hitls_feature_local_enable(HITLS_TLS_SUITE_CHACHA20_POLY1305_SHA256)
                    hitls_feature_local_enable(HITLS_TLS_SUITE_AES_128_CCM_SHA256)
                    hitls_feature_local_enable(HITLS_TLS_SUITE_AES_128_CCM_8_SHA256)
                endif()
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_GCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_GCM_SHA384)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_CCM)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_CCM)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256)
            endif()
            # No authentication
            hitls_feature_local_enable(HITLS_TLS_SUITE_DH_ANON_WITH_AES_128_GCM_SHA256)
            hitls_feature_local_enable(HITLS_TLS_SUITE_DH_ANON_WITH_AES_256_GCM_SHA384)
        endif()
        # RSA key exchange
        if(HITLS_TLS_SUITE_KX_RSA)
            # RSA authentication
            if(HITLS_TLS_SUITE_AUTH_RSA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_WITH_AES_128_GCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_WITH_AES_256_GCM_SHA384)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_GCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_GCM_SHA384)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_WITH_AES_128_CCM)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_WITH_AES_128_CCM_8)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_WITH_AES_256_CCM)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_WITH_AES_256_CCM_8)
            endif()
            # PSK authentication
            if(HITLS_TLS_SUITE_AUTH_PSK)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_GCM_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_GCM_SHA384)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256)
            endif()
        endif()

        # PSK Authentication
        if(HITLS_TLS_SUITE_AUTH_PSK)
            hitls_feature_local_enable(HITLS_TLS_SUITE_PSK_WITH_AES_128_GCM_SHA256)
            hitls_feature_local_enable(HITLS_TLS_SUITE_PSK_WITH_AES_256_GCM_SHA384)
            hitls_feature_local_enable(HITLS_TLS_SUITE_PSK_WITH_AES_256_CCM)
            hitls_feature_local_enable(HITLS_TLS_SUITE_PSK_WITH_CHACHA20_POLY1305_SHA256)
        endif()
        # SM2 Authentication
        if(HITLS_TLS_SUITE_AUTH_SM2)
            hitls_feature_local_enable(HITLS_TLS_SUITE_ECC_SM4_GCM_SM3)
        endif()
    endif()

    # CBC Cipher
    if(HITLS_TLS_SUITE_CIPHER_CBC)
        # ECDHE key exchange
        if(HITLS_TLS_SUITE_KX_ECDHE)
            # RSA authentication
            if(HITLS_TLS_SUITE_AUTH_RSA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_128_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_256_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_128_CBC_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_RSA_WITH_AES_256_CBC_SHA384)
            endif()
            # ECDSA authentication
            if(HITLS_TLS_SUITE_AUTH_ECDSA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384)
            endif()
            # PSK authentication
            if(HITLS_TLS_SUITE_AUTH_PSK)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_256_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_128_CBC_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_PSK_WITH_AES_256_CBC_SHA384)
            endif()
            # SM2 authentication
            if(HITLS_TLS_SUITE_AUTH_SM2)
                hitls_feature_local_enable(HITLS_TLS_SUITE_ECDHE_SM4_CBC_SM3)
            endif()
            # No authentication
            hitls_feature_local_enable(HITLS_TLS_SUITE_ECDH_ANON_WITH_AES_128_CBC_SHA)
            hitls_feature_local_enable(HITLS_TLS_SUITE_ECDH_ANON_WITH_AES_256_CBC_SHA)
        endif()
        # DHE key exchange
        if(HITLS_TLS_SUITE_KX_DHE)
            # RSA authentication
            if(HITLS_TLS_SUITE_AUTH_RSA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_128_CBC_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_RSA_WITH_AES_256_CBC_SHA256)
            endif()
            # DSS authentication
            if(HITLS_TLS_SUITE_AUTH_DSS)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_128_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_256_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_128_CBC_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_DSS_WITH_AES_256_CBC_SHA256)
            endif()
            # PSK authentication
            if(HITLS_TLS_SUITE_AUTH_PSK)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_128_CBC_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_DHE_PSK_WITH_AES_256_CBC_SHA384)
            endif()
            # No authentication
            hitls_feature_local_enable(HITLS_TLS_SUITE_DH_ANON_WITH_AES_128_CBC_SHA)
            hitls_feature_local_enable(HITLS_TLS_SUITE_DH_ANON_WITH_AES_256_CBC_SHA)
            hitls_feature_local_enable(HITLS_TLS_SUITE_DH_ANON_WITH_AES_128_CBC_SHA256)
            hitls_feature_local_enable(HITLS_TLS_SUITE_DH_ANON_WITH_AES_256_CBC_SHA256)
        endif()
        # RSA key exchange
        if(HITLS_TLS_SUITE_KX_RSA)
            # RSA authentication
            if(HITLS_TLS_SUITE_AUTH_RSA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_WITH_AES_128_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_WITH_AES_256_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_WITH_AES_128_CBC_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_WITH_AES_256_CBC_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA384)
            endif()
            # PSK authentication
            if(HITLS_TLS_SUITE_AUTH_PSK)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA256)
                hitls_feature_local_enable(HITLS_TLS_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA384)
            endif()
        endif()

        # PSK Authentication
        if(HITLS_TLS_SUITE_AUTH_PSK)
            hitls_feature_local_enable(HITLS_TLS_SUITE_PSK_WITH_AES_128_CBC_SHA)
            hitls_feature_local_enable(HITLS_TLS_SUITE_PSK_WITH_AES_256_CBC_SHA)
            hitls_feature_local_enable(HITLS_TLS_SUITE_PSK_WITH_AES_128_CBC_SHA256)
            hitls_feature_local_enable(HITLS_TLS_SUITE_PSK_WITH_AES_256_CBC_SHA384)
        endif()
        # SM2 Authentication
        if(HITLS_TLS_SUITE_AUTH_SM2)
            hitls_feature_local_enable(HITLS_TLS_SUITE_ECC_SM4_CBC_SM3)
        endif()
    endif()

    # SM TLS13
    if(HITLS_TLS_FEATURE_SM_TLS13)
        hitls_feature_local_enable(HITLS_TLS_SUITE_SM4_GCM_SM3)
        hitls_feature_local_enable(HITLS_TLS_SUITE_SM4_CCM_SM3)
    endif()
endmacro()


# Auto-enable all ASM features if any asm features is not enabled.
# 1. If any asm features is enabled, keep the enabled features.
# 2. If no asm features is enabled, enable all asm features depending on the enabled main features.
macro(hitls_auto_enable_asm_features)
    if(HITLS_ASM)
        set(_all_user_enable_asms "")
        set(_all_user_not_enable_asms "")

        # Check has asm enable
        get_cmake_property(_all_vars CACHE_VARIABLES)
        foreach(_var ${_all_vars})
            if(_var MATCHES "^HITLS_CRYPTO_.*_ARMV8$")
                String(REPLACE "_ARMV8" "" _main_feature ${_var})
                if(${_var})
                    list(APPEND _all_user_enable_asms ${_var})
                elseif(HITLS_ASM_ARMV8 AND ${_main_feature})
                    list(APPEND _all_user_not_enable_asms ${_var})
                endif()
            endif()
            if(_var MATCHES "^HITLS_CRYPTO_.*_ARMV7$")
                String(REPLACE "_ARMV7" "" _main_feature ${_var})
                if(${_var})
                    list(APPEND _all_user_enable_asms ${_var})
                elseif(HITLS_ASM_ARMV7 AND ${_main_feature})
                    list(APPEND _all_user_not_enable_asms ${_var})
                endif()
            endif()
            if(_var MATCHES "^HITLS_CRYPTO_.*_X8664$")
                String(REPLACE "_X8664" "" _main_feature ${_var})
                if(${_var})
                    list(APPEND _all_user_enable_asms ${_var})
                elseif(HITLS_ASM_X8664 AND ${_main_feature})
                    list(APPEND _all_user_not_enable_asms ${_var})
                endif()
            endif()
            if(_var MATCHES "^HITLS_CRYPTO_.*_X8664_AVX512$")
                String(REPLACE "_X8664_AVX512" "" _main_feature ${_var})
                if(${_var})
                    list(APPEND _all_user_enable_asms ${_var})
                elseif(HITLS_ASM_X8664_AVX512 AND ${_main_feature})
                    list(APPEND _all_user_not_enable_asms ${_var})
                endif()
            endif()
        endforeach()

        list(LENGTH _all_user_enable_asms _all_enable_asms_length)

        # If any asm features is not enabled, enable all asm features.
        if(_all_enable_asms_length EQUAL 0)
            foreach(_var ${_all_user_not_enable_asms})
                # unset in chache and enable on local variable to avoid force update cache value.
                unset(${_var} CACHE)
                set(${_var} ON)
                hitls_resolve_option_dependencies(${_var})
            endforeach()
        endif()

        unset(_all_user_enable_asms)
        unset(_all_user_not_enable_asms)
        unset(_all_enable_asms_length)
        unset(_all_vars)
        unset(_var)
    endif()
endmacro()


macro(hitls_special_depends_handle)
    if(HITLS_CRYPTO_ENTROPY)
        # if no entropy source is selected, default to getentropy and /dev/random if available.
        if(NOT HITLS_CRYPTO_ENTROPY_GETENTROPY AND NOT HITLS_CRYPTO_ENTROPY_DEVRANDOM AND
            NOT HITLS_CRYPTO_ENTROPY_SYS AND NOT HITLS_CRYPTO_ENTROPY_HARDWARE)
            hitls_feature_local_enable(HITLS_CRYPTO_ENTROPY_DEVRANDOM)
            hitls_feature_local_enable(HITLS_CRYPTO_ENTROPY_GETENTROPY)
        endif()
    endif()
    
    if(HITLS_CRYPTO_NIST_ECC_ACCELERATE AND NOT HITLS_CRYPTO_ECC)
        set(HITLS_CRYPTO_NIST_ECC_ACCELERATE OFF CACHE BOOL "" FORCE)
    endif()

    if(HITLS_CRYPTO_NIST_ECC_ACCELERATE AND HITLS_PLATFORM_INT128)
        hitls_feature_local_enable(HITLS_CRYPTO_NIST_USE_ACCEL)
    endif()

    if(NOT HITLS_SIXTY_FOUR_BITS)
        if(HITLS_CRYPTO_CURVE_NISTP192 OR
            HITLS_CRYPTO_CURVE_NISTP384 OR
            ((HITLS_CRYPTO_CURVE_NISTP224 OR HITLS_CRYPTO_CURVE_NISTP521) AND NOT HITLS_CRYPTO_NIST_USE_ACCEL) OR
            (HITLS_CRYPTO_CURVE_NISTP256 AND NOT HITLS_CRYPTO_CURVE_NISTP256_ASM AND
                NOT HITLS_CRYPTO_NIST_ECC_ACCELERATE AND NOT HITLS_CRYPTO_NIST_USE_ACCEL) OR
            (HITLS_CRYPTO_CURVE_SM2 AND NOT HITLS_CRYPTO_CURVE_SM2_ASM)
        )
            hitls_feature_local_enable(HITLS_CRYPTO_CURVE_MONT_NIST)
        endif()
    endif()

    if(HITLS_TLS)
        if(HITLS_BSL_UIO_UDP)
            if(NOT HITLS_TLS_FEATURE_ANTI_REPLAY)
                hitls_feature_local_enable(HITLS_TLS_FEATURE_ANTI_REPLAY)
            endif()
            if(NOT HITLS_TLS_FEATURE_DEFAULT_COOKIE)
                hitls_feature_local_enable(HITLS_TLS_FEATURE_DEFAULT_COOKIE)
            endif()
        endif()

        if(HITLS_TLS_FEATURE_PROVIDER_DYNAMIC)
            set(HITLS_TLS_FEATURE_PROVIDER_HARD_CODING OFF CACHE BOOL "" FORCE)
        endif()

        if(HITLS_TLS_FEATURE_PROVIDER)
            set(HITLS_TLS_CALLBACK_SAL              OFF CACHE BOOL "" FORCE)
            set(HITLS_TLS_CALLBACK_CERT             OFF CACHE BOOL "" FORCE)
            set(HITLS_TLS_CALLBACK_CRYPT            OFF CACHE BOOL "" FORCE)
        endif()

        if(NOT HITLS_TLS_FEATURE_PROVIDER AND NOT HITLS_TLS_CALLBACK_SAL)
            hitls_feature_local_enable(HITLS_TLS_FEATURE_PROVIDER)
        endif()

        if(HITLS_TLS_FEATURE_MTU_QUERY)
            if(NOT HITLS_TLS_PROTO_DTLS12 OR NOT HITLS_BSL_UIO_UDP)
                set(HITLS_TLS_FEATURE_MTU_QUERY     OFF CACHE BOOL "" FORCE)
            endif()
        endif()

        if(HITLS_TLS_FEATURE_MTU_QUERY AND NOT HITLS_BSL_UIO_MTU_QUERY)
            hitls_feature_local_enable(HITLS_BSL_UIO_MTU_QUERY)
        endif()
    endif()
endmacro()